export type NumberConfigKey =
  | "max_markets"
  | "max_open_orders"
  | "per_market_usd"
  | "quote_size_usd"
  | "min_daily_reward"
  | "min_market_liquidity_usd"
  | "min_market_volume_24h_usd"
  | "min_hours_to_end"
  | "max_market_spread_cents"
  | "max_market_data_age_minutes"
  | "min_market_score"
  | "max_spread_cents"
  | "safety_margin_cents"
  | "min_midpoint"
  | "max_midpoint"
  | "stale_book_ms"
  | "min_scoring_check_sec"
  | "max_position_usd"
  | "max_global_position_usd"
  | "exit_markup_cents"
  | "account_capital_usd"
  | "requote_drift_cents"
  | "min_depth_usd"
  | "cancel_bid_rank"
  | "depth_drop_pct"
  | "depth_drop_window_sec"
  | "fill_velocity_usd"
  | "fill_velocity_window_sec"
  | "mass_cancel_pct"
  | "mass_cancel_window_sec"
  | "requote_interval_sec"
  | "requote_jitter_sec"
  | "reconcile_interval_sec";

export type EventCategory = "all" | "placements" | "cancels" | "fills" | "rewards";
