#[allow(clippy::large_enum_variant)]
enum LiveRewardOrderUpdate {
    Changed(ManagedRewardOrder, RewardRiskEvent),
    Unchanged(RewardRiskEvent),
    Retryable(RewardRiskEvent),
}

struct LiveRewardFillUpdate {
    order: ManagedRewardOrder,
    fill: RewardFill,
    event: RewardRiskEvent,
    fill_size: Decimal,
    overdraft_warning: Option<RewardRiskEvent>,
}

fn live_cancel_result_is_unknown(order: &ManagedRewardOrder) -> bool {
    order.reason.contains("cancel result unknown")
}

static REWARD_CANCEL_IN_FLIGHT: OnceLock<Mutex<HashSet<String>>> = OnceLock::new();

struct RewardCancelInFlightGuard {
    external_order_id: String,
}

impl RewardCancelInFlightGuard {
    fn try_acquire(external_order_id: &str) -> Option<Self> {
        let mut in_flight = reward_cancel_in_flight_set()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        if !in_flight.insert(external_order_id.to_string()) {
            return None;
        }
        Some(Self {
            external_order_id: external_order_id.to_string(),
        })
    }
}

impl Drop for RewardCancelInFlightGuard {
    fn drop(&mut self) {
        let mut in_flight = reward_cancel_in_flight_set()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        in_flight.remove(&self.external_order_id);
    }
}

fn reward_cancel_in_flight_set() -> &'static Mutex<HashSet<String>> {
    REWARD_CANCEL_IN_FLIGHT.get_or_init(|| Mutex::new(HashSet::new()))
}

/// Internal order-ID prefixes generated by the rewards system (never submitted
/// to Polymarket).  Used to guard cancel/trade-sync against sending synthetic
/// IDs to the CLOB APIs.
const INTERNAL_ORDER_ID_PREFIXES: &[&str] = &[
    "rew_",
    "rewx_",
    "rewfill_",
    "rewevt_",
    "rewlive_",
    "rewexit_",
    "sim_rew_",
];

/// Returns `true` when `id` was generated internally (prefixes like `rew_`,
/// `rewx_`, `rewlive_`, `rewexit_`, `sim_rew_`) rather than submitted to
/// Polymarket (which returns plain UUIDs).  Guarding on this prevents sending
/// fake IDs to the CLOB cancel or trade-sync APIs.
fn is_internal_reward_order_id(id: &str) -> bool {
    INTERNAL_ORDER_ID_PREFIXES.iter().any(|prefix| id.starts_with(prefix))
}

async fn cancel_one_live_reward_order(
    connector: &LivePolymarketConnector,
    mut order: ManagedRewardOrder,
    reason: &str,
    _trace_id: &str,
) -> Result<LiveRewardOrderUpdate> {
    let Some(external_order_id) = order.external_order_id.clone() else {
        if live_submission_was_attempted(&order) {
            return Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_blocked_unknown_submission",
                RewardRiskSeverity::Critical,
                "cannot cancel a rewards order whose live submission result is unknown",
                json!({ "reason": order.reason }),
            )));
        }
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.reason = format!("local-only order cancelled: {reason}");
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true }),
            ),
        ));
    };

    if is_internal_reward_order_id(&external_order_id) {
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.external_order_id = None;
        order.reason = format!(
            "local-only order cancelled (internal id, never submitted): {reason}"
        );
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true, "internal_id": external_order_id }),
            ),
        ));
    }

    let Some(_cancel_guard) = RewardCancelInFlightGuard::try_acquire(&external_order_id) else {
        return Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
            &order,
            "reward_live_order_cancel_already_in_flight",
            RewardRiskSeverity::Info,
            "live rewards cancel already in flight for this external order",
            json!({ "external_order_id": external_order_id, "reason": reason }),
        )));
    };

    let request = LivePolymarketCancelOrderRequest {
        connector_name: POLYMARKET_CONNECTOR_NAME.to_string(),
        external_order_id: external_order_id.clone(),
    };
    match connector.cancel_order(&request).await {
        Ok(LivePolymarketCancelOutcome::Accepted(acceptance)) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel accepted; awaiting final reconciliation"
            );
            order.updated_at = acceptance.cancelled_at;
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_pending",
                    RewardRiskSeverity::Info,
                    format!(
                        "{} live order cancel accepted and awaiting final reconciliation: {reason}",
                        order.outcome
                    ),
                    json!({ "external_order_id": acceptance.external_order_id }),
                ),
            ))
        }
        Ok(LivePolymarketCancelOutcome::Rejected(rejection)) => {
            if polymarket_cancel_rejection_confirms_order_not_open(&rejection) {
                order.status = ManagedRewardOrderStatus::Cancelled;
                order.scoring = false;
                order.reason = format!(
                    "Polymarket reports order is no longer open; local remainder closed after cancel rejection: {}",
                    rejection.message
                );
                order.updated_at = OffsetDateTime::now_utc();
                return Ok(LiveRewardOrderUpdate::Changed(
                    order.clone(),
                    reward_live_event(
                        &order,
                        "reward_live_order_remote_not_open_closed",
                        RewardRiskSeverity::Info,
                        order.reason.clone(),
                        json!({
                            "code": rejection.code,
                            "external_order_id": external_order_id,
                            "cancel_reason": reason,
                        }),
                    ),
                ));
            }

            Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_rejected",
                RewardRiskSeverity::Warning,
                format!("live rewards cancel rejected: {}", rejection.message),
                json!({ "code": rejection.code, "external_order_id": external_order_id }),
            )))
        }
        Err(error) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel result unknown and awaiting final reconciliation: {error}"
            );
            order.updated_at = OffsetDateTime::now_utc();
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_unknown",
                    RewardRiskSeverity::Critical,
                    order.reason.clone(),
                    json!({ "external_order_id": external_order_id }),
                ),
            ))
        }
    }
}

fn apply_live_reward_fill_update(
    mut order: ManagedRewardOrder,
    account: &mut polyedge_application::RewardAccountState,
    positions: &mut HashMap<String, RewardPosition>,
    update: &ConnectorTradeFillUpdate,
    fill_id: &str,
    trace_id: &str,
    external_snapshot_includes_fill: bool,
) -> Option<LiveRewardFillUpdate> {
    let preserved_partial_fill_reason = (order.reason.contains("awaiting final reconciliation")
        || order.reason.contains("cancellation must be retried")
        || live_order_has_post_only_violation(&order)
        || (order.side == RewardOrderSide::Sell
            && order.status == ManagedRewardOrderStatus::ExitPending))
    .then(|| order.reason.clone());
    let remaining = (order.size - order.filled_size).max(Decimal::ZERO);
    let fill_size = Decimal::min(update.filled_quantity.value(), remaining)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if fill_size <= Decimal::ZERO {
        return None;
    }

    let price = update.fill_price.value();
    let fee = update.fee.value();
    let notional = (price * fill_size).round_dp(4);
    let now = OffsetDateTime::now_utc();
    let mut realized_pnl = Decimal::ZERO;
    let fill_role = reward_fill_role_for_live_order(&order);
    let mut overdraft_warning: Option<RewardRiskEvent> = None;

    if !external_snapshot_includes_fill {
        match order.side {
        RewardOrderSide::Buy => {
            let previous_available = account.available_usd;
            account.available_usd = (account.available_usd - notional - fee).max(Decimal::ZERO);
            if previous_available < notional + fee {
                overdraft_warning = Some(reward_live_event(
                    &order,
                    "reward_live_buy_fill_overdraft",
                    RewardRiskSeverity::Warning,
                    format!(
                        "buy fill deducted {notional:.4} + fee {fee:.4} from available_usd {previous_available:.4}; local balance clamped to zero — external account sync will correct",
                    ),
                    json!({
                        "previous_available_usd": previous_available,
                        "notional": notional,
                        "fee": fee,
                        "shortfall": (notional + fee - previous_available).round_dp(4),
                    }),
                ));
            }
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            let next_size = position.size + fill_size;
            if next_size > Decimal::ZERO {
                position.avg_price =
                    ((position.size * position.avg_price) + (fill_size * price)) / next_size;
            }
            position.size = next_size;
            position.updated_at = now;
        }
        RewardOrderSide::Sell => {
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            // Only realize PnL against a KNOWN cost basis. Selling inventory the
            // ledger doesn't track (no recorded buy yet) still credits the real
            // cash proceeds, but books zero PnL instead of fabricating a basis
            // from the sell price (which produced a spurious ~-fee PnL).
            realized_pnl = if position.avg_price > Decimal::ZERO && position.size > Decimal::ZERO {
                ((price - position.avg_price) * fill_size - fee).round_dp(4)
            } else {
                Decimal::ZERO
            };
            // Credit NET proceeds (notional - fee). Not clamped to zero: on dust
            // fills where fee > notional the small negative keeps available_usd
            // and realized_pnl mutually consistent.
            account.available_usd += (notional - fee).round_dp(4);
            account.realized_pnl += realized_pnl;
            position.size = (position.size - fill_size).max(Decimal::ZERO);
            position.realized_pnl += realized_pnl;
            position.updated_at = now;
        }
        }
        account.fees_paid += fee;
    }

    order.filled_size = (order.filled_size + fill_size).min(order.size);
    order.updated_at = now;
    if order.filled_size >= order.size {
        order.status = ManagedRewardOrderStatus::Filled;
        order.scoring = false;
        order.reason = "live rewards order fully filled on Polymarket".to_string();
    } else if let Some(reason) = preserved_partial_fill_reason {
        order.reason = format!("{reason}; live rewards order partially filled on Polymarket");
    } else {
        order.reason = "live rewards order partially filled on Polymarket".to_string();
    }

    let fill = RewardFill {
        id: fill_id.to_string(),
        order_id: order.id.clone(),
        account_id: order.account_id.clone(),
        condition_id: order.condition_id.clone(),
        token_id: order.token_id.clone(),
        outcome: order.outcome.clone(),
        side: order.side,
        price,
        size: fill_size,
        notional_usd: notional,
        role: fill_role,
        realized_pnl,
        reason: "live Polymarket trade reconciled".to_string(),
        trace_id: trace_id.to_string(),
        created_at: now,
    };
    let event = reward_live_event(
        &order,
        "reward_live_order_filled",
        RewardRiskSeverity::Info,
        format!(
            "{} live {} fill reconciled: {} @ {}",
            order.outcome,
            order.side.as_str(),
            fill_size,
            price
        ),
        json!({
            "fill_id": fill.id,
            "external_trade_id": update.external_trade_id,
            "external_order_id": update.external_order_id,
            "fill_size": fill_size,
            "price": price,
            "fee": fee,
            "realized_pnl": realized_pnl,
        }),
    );

    Some(LiveRewardFillUpdate {
        order,
        fill,
        event,
        fill_size,
        overdraft_warning,
    })
}

fn reward_fill_role_for_live_order(order: &ManagedRewardOrder) -> RewardFillRole {
    if order.side == RewardOrderSide::Sell
        && (order.reason.contains("taker") || order.reason.contains("non-post-only"))
    {
        RewardFillRole::Taker
    } else {
        RewardFillRole::Maker
    }
}

#[allow(clippy::too_many_arguments)]
fn plan_live_post_fill_orders(
    config: &RewardBotConfig,
    plans: &[RewardQuotePlan],
    entry: &ManagedRewardOrder,
    fill_size: Decimal,
    positions: &HashMap<String, RewardPosition>,
    _books: &HashMap<String, RewardOrderBook>,
    ai_min_confidence: Decimal,
    trace_id: &str,
) -> Vec<LiveRewardOrderUpdate> {
    if fill_size <= Decimal::ZERO {
        return Vec::new();
    }
    if entry.strategy_profile == RewardStrategyProfile::BalancedMerge {
        return Vec::new();
    }

    let post_fill_strategy = reward_post_fill_strategy(config, plans, entry, ai_min_confidence);
    match post_fill_strategy {
        PostFillStrategy::HoldAndRequote | PostFillStrategy::ExitAtMarkup => {
            let exit_price = match post_fill_strategy {
                PostFillStrategy::HoldAndRequote => ceil_reward_price_to_tick(entry.price),
                PostFillStrategy::ExitAtMarkup => ceil_reward_price_to_tick(Decimal::min(
                    Decimal::from_parts(99, 0, 0, false, 2),
                    entry.price + config.exit_markup_cents / Decimal::from(100_u64),
                )),
                PostFillStrategy::FlattenImmediately => unreachable!(),
            };
            let (reason, event_type) = match post_fill_strategy {
                PostFillStrategy::HoldAndRequote => (
                    "post-only hold-and-requote original-price exit",
                    "reward_live_hold_requote_exit_planned",
                ),
                PostFillStrategy::ExitAtMarkup => (
                    "post-fill exit at markup",
                    "reward_live_exit_planned",
                ),
                PostFillStrategy::FlattenImmediately => unreachable!(),
            };
            let mut exit = live_exit_order(entry, fill_size, exit_price, reason, trace_id);
            exit.status = ManagedRewardOrderStatus::ExitPending;
            let event = reward_live_event(
                &exit,
                event_type,
                RewardRiskSeverity::Info,
                "persisted post-fill rewards exit intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": true,
                    "trace_id": trace_id,
                }),
            );
            vec![LiveRewardOrderUpdate::Changed(exit, event)]
        }
        PostFillStrategy::FlattenImmediately => {
            let exit_floor = positions
                .get(&entry.token_id)
                .map(|position| position.avg_price)
                .filter(|price| *price > Decimal::ZERO)
                .map(|avg_price| Decimal::max(entry.price, avg_price))
                .unwrap_or(entry.price);
            let exit_price = ceil_reward_price_to_tick(exit_floor);
            let reason = "flatten immediately at non-loss floor";
            let mut exit = live_exit_order(
                entry,
                fill_size,
                exit_price,
                reason,
                trace_id,
            );
            exit.status = ManagedRewardOrderStatus::ExitPending;
            let event = reward_live_event(
                &exit,
                "reward_live_flatten_planned",
                RewardRiskSeverity::Info,
                "persisted post-fill rewards flatten intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": false,
                    "trace_id": trace_id,
                }),
            );
            vec![LiveRewardOrderUpdate::Changed(exit, event)]
        }
    }
}

async fn plan_live_balanced_merge_intent(
    state: &AppState,
    entry: &ManagedRewardOrder,
    fill: &RewardFill,
    positions: &HashMap<String, RewardPosition>,
    trace_id: &str,
) -> Result<(Vec<RewardMergeIntent>, Vec<RewardRiskEvent>)> {
    if entry.strategy_profile != RewardStrategyProfile::BalancedMerge
        || entry.side != RewardOrderSide::Buy
    {
        return Ok((Vec::new(), Vec::new()));
    }

    let yes_position = positions.values().find(|position| {
        position.account_id == entry.account_id
            && position.condition_id == entry.condition_id
            && position.size > Decimal::ZERO
            && position.outcome.trim().eq_ignore_ascii_case("yes")
    });
    let no_position = positions.values().find(|position| {
        position.account_id == entry.account_id
            && position.condition_id == entry.condition_id
            && position.size > Decimal::ZERO
            && position.outcome.trim().eq_ignore_ascii_case("no")
    });

    let (Some(yes_position), Some(no_position)) = (yes_position, no_position) else {
        return Ok((
            Vec::new(),
            vec![reward_live_event(
                entry,
                "reward_live_balanced_merge_waiting_for_pair",
                RewardRiskSeverity::Info,
                "balanced merge fill recorded; waiting for the opposite outcome inventory before merge",
                json!({
                    "source_fill_id": fill.id,
                    "filled_token_id": entry.token_id,
                    "filled_outcome": entry.outcome,
                }),
            )],
        ));
    };

    let mergeable_size = Decimal::min(yes_position.size, no_position.size)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if mergeable_size <= Decimal::ZERO {
        return Ok((Vec::new(), Vec::new()));
    }
    let already_planned_size = state
        .reward_bot_service
        .active_reward_merge_intent_size(&entry.account_id, &entry.condition_id)
        .await?
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    let merge_size = (mergeable_size - already_planned_size)
        .max(Decimal::ZERO)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if merge_size <= Decimal::ZERO {
        return Ok((Vec::new(), Vec::new()));
    }

    let now = OffsetDateTime::now_utc();
    let intent = RewardMergeIntent {
        id: format!("rewmerge_{}", sanitize_reward_id_fragment(&fill.id)),
        account_id: entry.account_id.clone(),
        condition_id: entry.condition_id.clone(),
        yes_token_id: yes_position.token_id.clone(),
        no_token_id: no_position.token_id.clone(),
        merge_size,
        yes_position_size: yes_position.size,
        no_position_size: no_position.size,
        yes_avg_price: yes_position.avg_price,
        no_avg_price: no_position.avg_price,
        status: RewardMergeIntentStatus::Unsupported,
        reason: "balanced merge pair is ready, but on-chain merge execution is not available in this build".to_string(),
        source_fill_id: fill.id.clone(),
        trace_id: trace_id.to_string(),
        created_at: now,
        updated_at: now,
    };
    let event = reward_live_event(
        entry,
        "reward_live_balanced_merge_intent_created",
        RewardRiskSeverity::Warning,
        "created a balanced merge intent for paired YES/NO inventory; execution is pending connector support",
        json!({
            "merge_intent_id": intent.id,
            "source_fill_id": fill.id,
            "yes_token_id": intent.yes_token_id,
            "no_token_id": intent.no_token_id,
            "merge_size": intent.merge_size,
            "yes_position_size": intent.yes_position_size,
            "no_position_size": intent.no_position_size,
            "already_planned_size": already_planned_size,
            "status": intent.status.as_str(),
        }),
    );

    Ok((vec![intent], vec![event]))
}

fn reward_post_fill_strategy(
    config: &RewardBotConfig,
    _plans: &[RewardQuotePlan],
    _entry: &ManagedRewardOrder,
    _ai_min_confidence: Decimal,
) -> PostFillStrategy {
    config.post_fill_strategy
}

fn live_exit_order(
    entry: &ManagedRewardOrder,
    size: Decimal,
    price: Decimal,
    reason: &str,
    trace_id: &str,
) -> ManagedRewardOrder {
    let now = OffsetDateTime::now_utc();
    ManagedRewardOrder {
        id: format!(
            "rewexit_{}_{}",
            now.unix_timestamp_nanos(),
            trace_id.trim_start_matches("trc_")
        ),
        account_id: entry.account_id.clone(),
        condition_id: entry.condition_id.clone(),
        token_id: entry.token_id.clone(),
        outcome: entry.outcome.clone(),
        side: RewardOrderSide::Sell,
        price,
        size,
        strategy_bucket: entry.strategy_bucket,
        strategy_profile: entry.strategy_profile,
        external_order_id: None,
        status: ManagedRewardOrderStatus::Planned,
        scoring: false,
        reason: reason.to_string(),
        filled_size: Decimal::ZERO,
        reward_earned: Decimal::ZERO,
        last_scored_at: None,
        created_at: now,
        updated_at: now,
    }
}

#[allow(clippy::too_many_arguments)]
async fn cancel_sibling_live_reward_orders(
    connector: &LivePolymarketConnector,
    working_orders: &mut HashMap<String, ManagedRewardOrder>,
    filled_order: &ManagedRewardOrder,
    sibling_cancelled: &mut HashSet<String>,
    state: &AppState,
    account: &mut RewardAccountState,
    _positions: &HashMap<String, RewardPosition>,
    report: &mut RewardBotRunReport,
    trace_id: &str,
) -> Result<()> {
    let sibling_ids = working_orders
        .values()
        .filter(|order| {
            is_sibling_live_buy_order(order, filled_order)
                && sibling_cancelled.insert(order.id.clone())
        })
        .map(|order| order.id.clone())
        .collect::<Vec<_>>();

    for sibling_id in sibling_ids {
        let Some(sibling) = working_orders.get(&sibling_id).cloned() else {
            continue;
        };
        match cancel_one_live_reward_order(
            connector,
            sibling.clone(),
            "sibling rewards quote cancelled after live fill",
            trace_id,
        )
        .await?
        {
            LiveRewardOrderUpdate::Changed(order, event) => {
                working_orders.insert(order.id.clone(), order.clone());
                if !live_cancel_result_is_unknown(&order) {
                    report.cancelled_orders += 1;
                    report.risk_cancelled_orders += 1;
                }
                persist_live_reward_updates(
                    state,
                    account,
                    Vec::new(), // positions unchanged during sibling cancel
                    vec![order],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
            LiveRewardOrderUpdate::Unchanged(event)
            | LiveRewardOrderUpdate::Retryable(event) => {
                let sibling = mark_sibling_cancel_for_retry(sibling);
                working_orders.insert(sibling.id.clone(), sibling.clone());
                persist_live_reward_updates(
                    state,
                    account,
                    Vec::new(), // positions unchanged during sibling cancel
                    vec![sibling],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
        }
    }
    Ok(())
}

fn is_sibling_live_buy_order(
    candidate: &ManagedRewardOrder,
    filled_order: &ManagedRewardOrder,
) -> bool {
    candidate.id != filled_order.id
        && candidate.condition_id == filled_order.condition_id
        && candidate.token_id != filled_order.token_id
        && candidate.side == RewardOrderSide::Buy
        && candidate.status.is_open_like()
}

fn mark_sibling_cancel_for_retry(mut sibling: ManagedRewardOrder) -> ManagedRewardOrder {
    sibling.scoring = false;
    sibling.reason = format!(
        "{}; sibling cancellation must be retried after live fill",
        sibling.reason
    );
    sibling.updated_at = OffsetDateTime::now_utc();
    sibling
}

fn deferred_live_exit_is_post_only(order: &ManagedRewardOrder) -> bool {
    if order.reason.contains("post_only=false") || order.reason.contains("flatten") {
        return false;
    }
    order.reason.contains("post_only=true")
        || order.reason.contains("post-only")
        || order.reason.contains("original-price exit")
        || order.reason.contains("exit at markup")
}
