enum LiveRewardOrderUpdate {
    Changed(ManagedRewardOrder, RewardRiskEvent),
    Unchanged(RewardRiskEvent),
}

struct LiveRewardFillUpdate {
    order: ManagedRewardOrder,
    fill: RewardFill,
    event: RewardRiskEvent,
    fill_size: Decimal,
}

fn live_cancel_result_is_unknown(order: &ManagedRewardOrder) -> bool {
    order.reason.contains("cancel result unknown")
}

/// Internal order-ID prefixes generated by the rewards system (never submitted
/// to Polymarket).  Used to guard cancel/trade-sync against sending synthetic
/// IDs to the CLOB APIs.
const INTERNAL_ORDER_ID_PREFIXES: &[&str] = &[
    "rew_",
    "rewx_",
    "rewfill_",
    "rewevt_",
    "rewlive_",
    "rewexit_",
    "sim_rew_",
];

/// Returns `true` when `id` was generated internally (prefixes like `rew_`,
/// `rewx_`, `rewlive_`, `rewexit_`, `sim_rew_`) rather than submitted to
/// Polymarket (which returns plain UUIDs).  Guarding on this prevents sending
/// fake IDs to the CLOB cancel or trade-sync APIs.
fn is_internal_reward_order_id(id: &str) -> bool {
    INTERNAL_ORDER_ID_PREFIXES.iter().any(|prefix| id.starts_with(prefix))
}

async fn cancel_one_live_reward_order(
    connector: &LivePolymarketConnector,
    mut order: ManagedRewardOrder,
    reason: &str,
    _trace_id: &str,
) -> Result<LiveRewardOrderUpdate> {
    let Some(external_order_id) = order.external_order_id.clone() else {
        if live_submission_was_attempted(&order) {
            return Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_blocked_unknown_submission",
                RewardRiskSeverity::Critical,
                "cannot cancel a rewards order whose live submission result is unknown",
                json!({ "reason": order.reason }),
            )));
        }
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.reason = format!("local-only order cancelled: {reason}");
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true }),
            ),
        ));
    };

    if is_internal_reward_order_id(&external_order_id) {
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.external_order_id = None;
        order.reason = format!(
            "local-only order cancelled (internal id, never submitted): {reason}"
        );
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true, "internal_id": external_order_id }),
            ),
        ));
    }

    let request = LivePolymarketCancelOrderRequest {
        connector_name: POLYMARKET_CONNECTOR_NAME.to_string(),
        external_order_id: external_order_id.clone(),
    };
    match connector.cancel_order(&request).await {
        Ok(LivePolymarketCancelOutcome::Accepted(acceptance)) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel accepted; awaiting final reconciliation"
            );
            order.updated_at = acceptance.cancelled_at;
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_pending",
                    RewardRiskSeverity::Info,
                    format!(
                        "{} live order cancel accepted and awaiting final reconciliation: {reason}",
                        order.outcome
                    ),
                    json!({ "external_order_id": acceptance.external_order_id }),
                ),
            ))
        }
        Ok(LivePolymarketCancelOutcome::Rejected(rejection)) => {
            Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_rejected",
                RewardRiskSeverity::Warning,
                format!("live rewards cancel rejected: {}", rejection.message),
                json!({ "code": rejection.code, "external_order_id": external_order_id }),
            )))
        }
        Err(error) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel result unknown and awaiting final reconciliation: {error}"
            );
            order.updated_at = OffsetDateTime::now_utc();
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_unknown",
                    RewardRiskSeverity::Critical,
                    order.reason.clone(),
                    json!({ "external_order_id": external_order_id }),
                ),
            ))
        }
    }
}

fn apply_live_reward_fill_update(
    mut order: ManagedRewardOrder,
    account: &mut polyedge_application::RewardAccountState,
    positions: &mut HashMap<String, RewardPosition>,
    update: &ConnectorTradeFillUpdate,
    fill_id: &str,
    trace_id: &str,
) -> Option<LiveRewardFillUpdate> {
    let preserved_partial_fill_reason = (order.reason.contains("awaiting final reconciliation")
        || order.reason.contains("cancellation must be retried")
        || live_order_has_post_only_violation(&order)
        || (order.side == RewardOrderSide::Sell
            && order.status == ManagedRewardOrderStatus::ExitPending))
    .then(|| order.reason.clone());
    let remaining = (order.size - order.filled_size).max(Decimal::ZERO);
    let fill_size = Decimal::min(update.filled_quantity.value(), remaining)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if fill_size <= Decimal::ZERO {
        return None;
    }

    let price = update.fill_price.value();
    let fee = update.fee.value();
    let notional = (price * fill_size).round_dp(4);
    let now = OffsetDateTime::now_utc();
    let mut realized_pnl = Decimal::ZERO;
    let fill_role = reward_fill_role_for_live_order(&order);

    match order.side {
        RewardOrderSide::Buy => {
            account.available_usd = (account.available_usd - notional - fee).max(Decimal::ZERO);
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            let next_size = position.size + fill_size;
            if next_size > Decimal::ZERO {
                position.avg_price =
                    ((position.size * position.avg_price) + (fill_size * price)) / next_size;
            }
            position.size = next_size;
            position.updated_at = now;
        }
        RewardOrderSide::Sell => {
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            // Only realize PnL against a KNOWN cost basis. Selling inventory the
            // ledger doesn't track (no recorded buy yet) still credits the real
            // cash proceeds, but books zero PnL instead of fabricating a basis
            // from the sell price (which produced a spurious ~-fee PnL).
            realized_pnl = if position.avg_price > Decimal::ZERO && position.size > Decimal::ZERO {
                ((price - position.avg_price) * fill_size - fee).round_dp(4)
            } else {
                Decimal::ZERO
            };
            // Credit NET proceeds (notional - fee). Not clamped to zero: on dust
            // fills where fee > notional the small negative keeps available_usd
            // and realized_pnl mutually consistent.
            account.available_usd += (notional - fee).round_dp(4);
            account.realized_pnl += realized_pnl;
            position.size = (position.size - fill_size).max(Decimal::ZERO);
            position.realized_pnl += realized_pnl;
            position.updated_at = now;
        }
    }
    account.fees_paid += fee;

    order.filled_size = (order.filled_size + fill_size).min(order.size);
    order.updated_at = now;
    if order.filled_size >= order.size {
        order.status = ManagedRewardOrderStatus::Filled;
        order.scoring = false;
        order.reason = "live rewards order fully filled on Polymarket".to_string();
    } else if let Some(reason) = preserved_partial_fill_reason {
        order.reason = format!("{reason}; live rewards order partially filled on Polymarket");
    } else {
        order.reason = "live rewards order partially filled on Polymarket".to_string();
    }

    let fill = RewardFill {
        id: fill_id.to_string(),
        order_id: order.id.clone(),
        account_id: order.account_id.clone(),
        condition_id: order.condition_id.clone(),
        token_id: order.token_id.clone(),
        outcome: order.outcome.clone(),
        side: order.side,
        price,
        size: fill_size,
        notional_usd: notional,
        role: fill_role,
        realized_pnl,
        reason: "live Polymarket trade reconciled".to_string(),
        trace_id: trace_id.to_string(),
        created_at: now,
    };
    let event = reward_live_event(
        &order,
        "reward_live_order_filled",
        RewardRiskSeverity::Info,
        format!(
            "{} live {} fill reconciled: {} @ {}",
            order.outcome,
            order.side.as_str(),
            fill_size,
            price
        ),
        json!({
            "fill_id": fill.id,
            "external_trade_id": update.external_trade_id,
            "external_order_id": update.external_order_id,
            "fill_size": fill_size,
            "price": price,
            "fee": fee,
            "realized_pnl": realized_pnl,
        }),
    );

    Some(LiveRewardFillUpdate {
        order,
        fill,
        event,
        fill_size,
    })
}

fn reward_fill_role_for_live_order(order: &ManagedRewardOrder) -> RewardFillRole {
    if order.side == RewardOrderSide::Sell && order.reason.contains("flatten") {
        RewardFillRole::Taker
    } else {
        RewardFillRole::Maker
    }
}

fn plan_live_post_fill_orders(
    config: &RewardBotConfig,
    entry: &ManagedRewardOrder,
    fill_size: Decimal,
    positions: &HashMap<String, RewardPosition>,
    books: &HashMap<String, RewardOrderBook>,
    trace_id: &str,
) -> Vec<LiveRewardOrderUpdate> {
    if fill_size <= Decimal::ZERO {
        return Vec::new();
    }

    match config.post_fill_strategy {
        PostFillStrategy::HoldAndRequote => Vec::new(),
        PostFillStrategy::ExitAtMarkup => {
            let avg_price = positions
                .get(&entry.token_id)
                .map(|position| position.avg_price)
                .filter(|price| *price > Decimal::ZERO)
                .unwrap_or(entry.price);
            let exit_price = floor_reward_price_to_tick(Decimal::min(
                Decimal::from_parts(99, 0, 0, false, 2),
                avg_price + config.exit_markup_cents / Decimal::from(100_u64),
            ));
            let mut exit = live_exit_order(
                entry,
                fill_size,
                exit_price,
                "post-fill exit at markup",
                trace_id,
            );
            exit.status = ManagedRewardOrderStatus::ExitPending;
            let event = reward_live_event(
                &exit,
                "reward_live_exit_planned",
                RewardRiskSeverity::Info,
                "persisted post-fill rewards exit intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": true,
                    "trace_id": trace_id,
                }),
            );
            vec![LiveRewardOrderUpdate::Changed(exit, event)]
        }
        PostFillStrategy::FlattenImmediately => {
            let Some(best_bid) = books
                .get(&entry.token_id)
                .and_then(|book| book.bids.first())
                .map(|level| level.price)
                .filter(|price| *price > Decimal::ZERO)
            else {
                let avg_price = positions
                    .get(&entry.token_id)
                    .map(|position| position.avg_price)
                    .filter(|price| *price > Decimal::ZERO)
                    .unwrap_or(entry.price);
                let mut exit = live_exit_order(
                    entry,
                    fill_size,
                    floor_reward_price_to_tick(avg_price),
                    "flatten deferred until bid liquidity is observed",
                    trace_id,
                );
                exit.status = ManagedRewardOrderStatus::ExitPending;
                let event = reward_live_event(
                    &exit,
                    "reward_live_flatten_deferred",
                    RewardRiskSeverity::Warning,
                    "deferred rewards flatten because no bid liquidity is available",
                    json!({
                        "token_id": entry.token_id,
                        "size": fill_size,
                        "deferred_price": exit.price,
                        "trace_id": trace_id,
                    }),
                );
                return vec![LiveRewardOrderUpdate::Changed(exit, event)];
            };
            let mut exit = live_exit_order(
                entry,
                fill_size,
                floor_reward_price_to_tick(best_bid),
                "post-fill flatten immediately",
                trace_id,
            );
            exit.status = ManagedRewardOrderStatus::ExitPending;
            let event = reward_live_event(
                &exit,
                "reward_live_flatten_planned",
                RewardRiskSeverity::Info,
                "persisted post-fill rewards flatten intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": false,
                    "trace_id": trace_id,
                }),
            );
            vec![LiveRewardOrderUpdate::Changed(exit, event)]
        }
    }
}

fn live_exit_order(
    entry: &ManagedRewardOrder,
    size: Decimal,
    price: Decimal,
    reason: &str,
    trace_id: &str,
) -> ManagedRewardOrder {
    let now = OffsetDateTime::now_utc();
    ManagedRewardOrder {
        id: format!(
            "rewexit_{}_{}",
            now.unix_timestamp_nanos(),
            trace_id.trim_start_matches("trc_")
        ),
        account_id: entry.account_id.clone(),
        condition_id: entry.condition_id.clone(),
        token_id: entry.token_id.clone(),
        outcome: entry.outcome.clone(),
        side: RewardOrderSide::Sell,
        price,
        size,
        external_order_id: None,
        status: ManagedRewardOrderStatus::Planned,
        scoring: false,
        reason: reason.to_string(),
        filled_size: Decimal::ZERO,
        reward_earned: Decimal::ZERO,
        last_scored_at: None,
        created_at: now,
        updated_at: now,
    }
}

async fn cancel_sibling_live_reward_orders(
    connector: &LivePolymarketConnector,
    working_orders: &mut HashMap<String, ManagedRewardOrder>,
    filled_order: &ManagedRewardOrder,
    sibling_cancelled: &mut HashSet<String>,
    state: &AppState,
    account: &mut RewardAccountState,
    positions: &HashMap<String, RewardPosition>,
    report: &mut RewardBotRunReport,
    trace_id: &str,
) -> Result<()> {
    let sibling_ids = working_orders
        .values()
        .filter(|order| {
            order.id != filled_order.id
                && order.condition_id == filled_order.condition_id
                && order.token_id != filled_order.token_id
                && order.status.is_open_like()
                && sibling_cancelled.insert(order.id.clone())
        })
        .map(|order| order.id.clone())
        .collect::<Vec<_>>();

    for sibling_id in sibling_ids {
        let Some(sibling) = working_orders.get(&sibling_id).cloned() else {
            continue;
        };
        match cancel_one_live_reward_order(
            connector,
            sibling.clone(),
            "sibling rewards quote cancelled after live fill",
            trace_id,
        )
        .await?
        {
            LiveRewardOrderUpdate::Changed(order, event) => {
                working_orders.insert(order.id.clone(), order.clone());
                if !live_cancel_result_is_unknown(&order) {
                    report.cancelled_orders += 1;
                    report.risk_cancelled_orders += 1;
                }
                persist_live_reward_updates(
                    state,
                    account,
                    positions.values().cloned().collect(),
                    vec![order],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
            LiveRewardOrderUpdate::Unchanged(event) => {
                let sibling = mark_sibling_cancel_for_retry(sibling);
                working_orders.insert(sibling.id.clone(), sibling.clone());
                persist_live_reward_updates(
                    state,
                    account,
                    positions.values().cloned().collect(),
                    vec![sibling],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
        }
    }
    Ok(())
}

fn mark_sibling_cancel_for_retry(mut sibling: ManagedRewardOrder) -> ManagedRewardOrder {
    sibling.scoring = false;
    sibling.reason = format!(
        "{}; sibling cancellation must be retried after live fill",
        sibling.reason
    );
    sibling.updated_at = OffsetDateTime::now_utc();
    sibling
}

fn deferred_live_exit_is_post_only(order: &ManagedRewardOrder) -> bool {
    order.reason.contains("post-only")
        || order.reason.contains("exit at markup")
        || order.reason.contains("post_only=true")
}
