#[allow(clippy::large_enum_variant)]
enum LiveRewardOrderUpdate {
    Changed(ManagedRewardOrder, RewardRiskEvent),
    Unchanged(RewardRiskEvent),
    Retryable(RewardRiskEvent),
}

struct LiveRewardFillUpdate {
    order: ManagedRewardOrder,
    fill: RewardFill,
    event: RewardRiskEvent,
    fill_size: Decimal,
    overdraft_warning: Option<RewardRiskEvent>,
}

struct RewardPostFillStrategyDecision {
    strategy: PostFillStrategy,
    source: RewardExitStrategySource,
    floor_price: Decimal,
    adaptive_event: Option<RewardRiskEvent>,
}

#[derive(Debug, Clone)]
struct AdaptiveExitDecision {
    selected_strategy: PostFillStrategy,
    fallback_strategy: PostFillStrategy,
    floor_price: Decimal,
    best_bid: Option<Decimal>,
    best_ask: Option<Decimal>,
    exit_notional_usd: Decimal,
    bid_depth_at_floor_usd: Decimal,
    required_depth_usd: Decimal,
    min_flatten_bid: Decimal,
    can_flatten_non_loss: bool,
    plan_eligible: Option<bool>,
    quote_readiness: Option<&'static str>,
    plan_ineligible: bool,
    plan_healthy: bool,
    hard_risk_reasons: Vec<String>,
    reason: String,
}

fn live_cancel_result_is_unknown(order: &ManagedRewardOrder) -> bool {
    order.reason.contains("cancel result unknown")
}

static REWARD_CANCEL_IN_FLIGHT: OnceLock<Mutex<HashSet<String>>> = OnceLock::new();

struct RewardCancelInFlightGuard {
    external_order_id: String,
}

impl RewardCancelInFlightGuard {
    fn try_acquire(external_order_id: &str) -> Option<Self> {
        let mut in_flight = reward_cancel_in_flight_set()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        if !in_flight.insert(external_order_id.to_string()) {
            return None;
        }
        Some(Self {
            external_order_id: external_order_id.to_string(),
        })
    }
}

impl Drop for RewardCancelInFlightGuard {
    fn drop(&mut self) {
        let mut in_flight = reward_cancel_in_flight_set()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        in_flight.remove(&self.external_order_id);
    }
}

fn reward_cancel_in_flight_set() -> &'static Mutex<HashSet<String>> {
    REWARD_CANCEL_IN_FLIGHT.get_or_init(|| Mutex::new(HashSet::new()))
}

/// Internal order-ID prefixes generated by the rewards system (never submitted
/// to Polymarket).  Used to guard cancel/trade-sync against sending synthetic
/// IDs to the CLOB APIs.
const INTERNAL_ORDER_ID_PREFIXES: &[&str] = &[
    "rew_",
    "rewx_",
    "rewfill_",
    "rewevt_",
    "rewlive_",
    "rewexit_",
    "sim_rew_",
];

/// Returns `true` when `id` was generated internally (prefixes like `rew_`,
/// `rewx_`, `rewlive_`, `rewexit_`, `sim_rew_`) rather than submitted to
/// Polymarket (which returns plain UUIDs).  Guarding on this prevents sending
/// fake IDs to the CLOB cancel or trade-sync APIs.
fn is_internal_reward_order_id(id: &str) -> bool {
    INTERNAL_ORDER_ID_PREFIXES.iter().any(|prefix| id.starts_with(prefix))
}

async fn cancel_one_live_reward_order(
    connector: &LivePolymarketConnector,
    mut order: ManagedRewardOrder,
    reason: &str,
    _trace_id: &str,
) -> Result<LiveRewardOrderUpdate> {
    let Some(external_order_id) = order.external_order_id.clone() else {
        if live_submission_was_attempted(&order) {
            return Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_blocked_unknown_submission",
                RewardRiskSeverity::Critical,
                "cannot cancel a rewards order whose live submission result is unknown",
                json!({ "reason": order.reason }),
            )));
        }
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.reason = format!("local-only order cancelled: {reason}");
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true }),
            ),
        ));
    };

    if is_internal_reward_order_id(&external_order_id) {
        order.status = ManagedRewardOrderStatus::Cancelled;
        order.scoring = false;
        order.external_order_id = None;
        order.reason = format!(
            "local-only order cancelled (internal id, never submitted): {reason}"
        );
        order.updated_at = OffsetDateTime::now_utc();
        return Ok(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                &order,
                "reward_live_order_cancelled",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({ "local_only": true, "internal_id": external_order_id }),
            ),
        ));
    }

    let Some(_cancel_guard) = RewardCancelInFlightGuard::try_acquire(&external_order_id) else {
        return Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
            &order,
            "reward_live_order_cancel_already_in_flight",
            RewardRiskSeverity::Info,
            "live rewards cancel already in flight for this external order",
            json!({ "external_order_id": external_order_id, "reason": reason }),
        )));
    };

    let request = LivePolymarketCancelOrderRequest {
        connector_name: POLYMARKET_CONNECTOR_NAME.to_string(),
        external_order_id: external_order_id.clone(),
    };
    match connector.cancel_order(&request).await {
        Ok(LivePolymarketCancelOutcome::Accepted(acceptance)) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel accepted; awaiting final reconciliation"
            );
            order.updated_at = acceptance.cancelled_at;
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_pending",
                    RewardRiskSeverity::Info,
                    format!(
                        "{} live order cancel accepted and awaiting final reconciliation: {reason}",
                        order.outcome
                    ),
                    json!({ "external_order_id": acceptance.external_order_id }),
                ),
            ))
        }
        Ok(LivePolymarketCancelOutcome::Rejected(rejection)) => {
            if polymarket_cancel_rejection_confirms_order_not_open(&rejection) {
                order.status = ManagedRewardOrderStatus::Cancelled;
                order.scoring = false;
                order.reason = format!(
                    "Polymarket reports order is no longer open; local remainder closed after cancel rejection: {}",
                    rejection.message
                );
                order.updated_at = OffsetDateTime::now_utc();
                return Ok(LiveRewardOrderUpdate::Changed(
                    order.clone(),
                    reward_live_event(
                        &order,
                        "reward_live_order_remote_not_open_closed",
                        RewardRiskSeverity::Info,
                        order.reason.clone(),
                        json!({
                            "code": rejection.code,
                            "external_order_id": external_order_id,
                            "cancel_reason": reason,
                        }),
                    ),
                ));
            }

            Ok(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                &order,
                "reward_live_order_cancel_rejected",
                RewardRiskSeverity::Warning,
                format!("live rewards cancel rejected: {}", rejection.message),
                json!({ "code": rejection.code, "external_order_id": external_order_id }),
            )))
        }
        Err(error) => {
            let prior_reason = order.reason.clone();
            order.status = ManagedRewardOrderStatus::Open;
            order.scoring = false;
            order.reason = format!(
                "{prior_reason}; cancel requested because {reason}; cancel result unknown and awaiting final reconciliation: {error}"
            );
            order.updated_at = OffsetDateTime::now_utc();
            Ok(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    &order,
                    "reward_live_order_cancel_unknown",
                    RewardRiskSeverity::Critical,
                    order.reason.clone(),
                    json!({ "external_order_id": external_order_id }),
                ),
            ))
        }
    }
}

fn apply_live_reward_fill_update(
    mut order: ManagedRewardOrder,
    account: &mut polyedge_application::RewardAccountState,
    positions: &mut HashMap<String, RewardPosition>,
    update: &ConnectorTradeFillUpdate,
    fill_id: &str,
    trace_id: &str,
    external_snapshot_includes_fill: bool,
) -> Option<LiveRewardFillUpdate> {
    let preserved_partial_fill_reason = (order.reason.contains("awaiting final reconciliation")
        || order.reason.contains("cancellation must be retried")
        || live_order_has_post_only_violation(&order)
        || (order.side == RewardOrderSide::Sell
            && order.status == ManagedRewardOrderStatus::ExitPending))
    .then(|| order.reason.clone());
    let remaining = (order.size - order.filled_size).max(Decimal::ZERO);
    let fill_size = Decimal::min(update.filled_quantity.value(), remaining)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if fill_size <= Decimal::ZERO {
        return None;
    }

    let price = update.fill_price.value();
    let fee = update.fee.value();
    let notional = (price * fill_size).round_dp(4);
    let now = OffsetDateTime::now_utc();
    let mut realized_pnl = Decimal::ZERO;
    let fill_role = reward_fill_role_for_live_order(&order);
    let mut overdraft_warning: Option<RewardRiskEvent> = None;

    if !external_snapshot_includes_fill {
        match order.side {
        RewardOrderSide::Buy => {
            let previous_available = account.available_usd;
            account.available_usd = (account.available_usd - notional - fee).max(Decimal::ZERO);
            if previous_available < notional + fee {
                overdraft_warning = Some(reward_live_event(
                    &order,
                    "reward_live_buy_fill_overdraft",
                    RewardRiskSeverity::Warning,
                    format!(
                        "buy fill deducted {notional:.4} + fee {fee:.4} from available_usd {previous_available:.4}; local balance clamped to zero — external account sync will correct",
                    ),
                    json!({
                        "previous_available_usd": previous_available,
                        "notional": notional,
                        "fee": fee,
                        "shortfall": (notional + fee - previous_available).round_dp(4),
                    }),
                ));
            }
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            let next_size = position.size + fill_size;
            if next_size > Decimal::ZERO {
                position.avg_price =
                    ((position.size * position.avg_price) + (fill_size * price)) / next_size;
            }
            position.size = next_size;
            position.updated_at = now;
        }
        RewardOrderSide::Sell => {
            let position =
                positions
                    .entry(order.token_id.clone())
                    .or_insert_with(|| RewardPosition {
                        account_id: order.account_id.clone(),
                        condition_id: order.condition_id.clone(),
                        token_id: order.token_id.clone(),
                        outcome: order.outcome.clone(),
                        size: Decimal::ZERO,
                        avg_price: Decimal::ZERO,
                        realized_pnl: Decimal::ZERO,
                        updated_at: now,
                    });
            // Only realize PnL against a KNOWN cost basis. Selling inventory the
            // ledger doesn't track (no recorded buy yet) still credits the real
            // cash proceeds, but books zero PnL instead of fabricating a basis
            // from the sell price (which produced a spurious ~-fee PnL).
            realized_pnl = if position.avg_price > Decimal::ZERO && position.size > Decimal::ZERO {
                ((price - position.avg_price) * fill_size - fee).round_dp(4)
            } else {
                Decimal::ZERO
            };
            // Credit NET proceeds (notional - fee). Not clamped to zero: on dust
            // fills where fee > notional the small negative keeps available_usd
            // and realized_pnl mutually consistent.
            account.available_usd += (notional - fee).round_dp(4);
            account.realized_pnl += realized_pnl;
            position.size = (position.size - fill_size).max(Decimal::ZERO);
            position.realized_pnl += realized_pnl;
            position.updated_at = now;
        }
        }
        account.fees_paid += fee;
    }

    order.filled_size = (order.filled_size + fill_size).min(order.size);
    order.updated_at = now;
    if order.filled_size >= order.size {
        order.status = ManagedRewardOrderStatus::Filled;
        order.scoring = false;
        order.reason = "live rewards order fully filled on Polymarket".to_string();
    } else if let Some(reason) = preserved_partial_fill_reason {
        order.reason = format!("{reason}; live rewards order partially filled on Polymarket");
    } else {
        order.reason = "live rewards order partially filled on Polymarket".to_string();
    }

    let fill = RewardFill {
        id: fill_id.to_string(),
        order_id: order.id.clone(),
        account_id: order.account_id.clone(),
        condition_id: order.condition_id.clone(),
        token_id: order.token_id.clone(),
        outcome: order.outcome.clone(),
        side: order.side,
        price,
        size: fill_size,
        notional_usd: notional,
        role: fill_role,
        realized_pnl,
        reason: "live Polymarket trade reconciled".to_string(),
        trace_id: trace_id.to_string(),
        created_at: now,
    };
    let event = reward_live_event(
        &order,
        "reward_live_order_filled",
        RewardRiskSeverity::Info,
        format!(
            "{} live {} fill reconciled: {} @ {}",
            order.outcome,
            order.side.as_str(),
            fill_size,
            price
        ),
        json!({
            "fill_id": fill.id,
            "external_trade_id": update.external_trade_id,
            "external_order_id": update.external_order_id,
            "fill_size": fill_size,
            "price": price,
            "fee": fee,
            "realized_pnl": realized_pnl,
        }),
    );

    Some(LiveRewardFillUpdate {
        order,
        fill,
        event,
        fill_size,
        overdraft_warning,
    })
}

fn reward_fill_role_for_live_order(order: &ManagedRewardOrder) -> RewardFillRole {
    if order.side == RewardOrderSide::Sell
        && (order.reason.contains("taker") || order.reason.contains("non-post-only"))
    {
        RewardFillRole::Taker
    } else {
        RewardFillRole::Maker
    }
}

#[allow(clippy::too_many_arguments)]
fn plan_live_post_fill_orders(
    config: &RewardBotConfig,
    plans: &[RewardQuotePlan],
    entry: &ManagedRewardOrder,
    fill_size: Decimal,
    positions: &HashMap<String, RewardPosition>,
    _books: &HashMap<String, RewardOrderBook>,
    ai_min_confidence: Decimal,
    trace_id: &str,
) -> Vec<LiveRewardOrderUpdate> {
    if fill_size <= Decimal::ZERO {
        return Vec::new();
    }
    if entry.strategy_profile == RewardStrategyProfile::BalancedMerge {
        return Vec::new();
    }

    let strategy_decision = reward_post_fill_strategy(
        config,
        plans,
        entry,
        fill_size,
        positions,
        _books,
        ai_min_confidence,
    );
    let mut updates = strategy_decision
        .adaptive_event
        .map(LiveRewardOrderUpdate::Unchanged)
        .into_iter()
        .collect::<Vec<_>>();
    let post_fill_strategy = strategy_decision.strategy;
    match post_fill_strategy {
        PostFillStrategy::HoldAndRequote | PostFillStrategy::ExitAtMarkup => {
            let exit_price = match post_fill_strategy {
                PostFillStrategy::HoldAndRequote => strategy_decision.floor_price,
                PostFillStrategy::ExitAtMarkup => ceil_reward_price_to_tick(Decimal::max(
                    strategy_decision.floor_price,
                    Decimal::min(
                        Decimal::from_parts(99, 0, 0, false, 2),
                        entry.price + config.exit_markup_cents / Decimal::from(100_u64),
                    ),
                )),
                PostFillStrategy::FlattenImmediately => unreachable!(),
                PostFillStrategy::Adaptive => unreachable!(),
            };
            let (reason, event_type) = match post_fill_strategy {
                PostFillStrategy::HoldAndRequote => (
                    "post-only hold-and-requote original-price exit",
                    "reward_live_hold_requote_exit_planned",
                ),
                PostFillStrategy::ExitAtMarkup => (
                    "post-fill exit at markup",
                    "reward_live_exit_planned",
                ),
                PostFillStrategy::FlattenImmediately => unreachable!(),
                PostFillStrategy::Adaptive => unreachable!(),
            };
            let mut exit = live_exit_order(entry, fill_size, exit_price, reason, trace_id);
            exit.status = ManagedRewardOrderStatus::ExitPending;
            exit.exit_strategy_source = strategy_decision.source;
            exit.exit_strategy_selected = Some(post_fill_strategy);
            exit.exit_floor_price = Some(strategy_decision.floor_price);
            let event = reward_live_event(
                &exit,
                event_type,
                RewardRiskSeverity::Info,
                "persisted post-fill rewards exit intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": true,
                    "trace_id": trace_id,
                }),
            );
            updates.push(LiveRewardOrderUpdate::Changed(exit, event));
            updates
        }
        PostFillStrategy::FlattenImmediately => {
            let exit_floor = strategy_decision.floor_price;
            let exit_price = exit_floor;
            let reason = "flatten immediately at non-loss floor";
            let mut exit = live_exit_order(
                entry,
                fill_size,
                exit_price,
                reason,
                trace_id,
            );
            exit.status = ManagedRewardOrderStatus::ExitPending;
            exit.exit_strategy_source = strategy_decision.source;
            exit.exit_strategy_selected = Some(PostFillStrategy::FlattenImmediately);
            exit.exit_floor_price = Some(strategy_decision.floor_price);
            let event = reward_live_event(
                &exit,
                "reward_live_flatten_planned",
                RewardRiskSeverity::Info,
                "persisted post-fill rewards flatten intent before live submission",
                json!({
                    "token_id": entry.token_id,
                    "size": fill_size,
                    "price": exit.price,
                    "post_only": false,
                    "trace_id": trace_id,
                }),
            );
            updates.push(LiveRewardOrderUpdate::Changed(exit, event));
            updates
        }
        PostFillStrategy::Adaptive => unreachable!(),
    }
}

async fn plan_live_balanced_merge_intent(
    state: &AppState,
    config: &RewardBotConfig,
    entry: &ManagedRewardOrder,
    fill: &RewardFill,
    positions: &HashMap<String, RewardPosition>,
    trace_id: &str,
) -> Result<(Vec<RewardMergeIntent>, Vec<RewardRiskEvent>)> {
    if entry.strategy_profile != RewardStrategyProfile::BalancedMerge
        || entry.side != RewardOrderSide::Buy
    {
        return Ok((Vec::new(), Vec::new()));
    }

    let yes_position = positions.values().find(|position| {
        position.account_id == entry.account_id
            && position.condition_id == entry.condition_id
            && position.size > Decimal::ZERO
            && position.outcome.trim().eq_ignore_ascii_case("yes")
    });
    let no_position = positions.values().find(|position| {
        position.account_id == entry.account_id
            && position.condition_id == entry.condition_id
            && position.size > Decimal::ZERO
            && position.outcome.trim().eq_ignore_ascii_case("no")
    });

    let (Some(yes_position), Some(no_position)) = (yes_position, no_position) else {
        return Ok((
            Vec::new(),
            vec![reward_live_event(
                entry,
                "reward_live_balanced_merge_waiting_for_pair",
                RewardRiskSeverity::Info,
                "balanced merge fill recorded; waiting for the opposite outcome inventory before merge",
                json!({
                    "source_fill_id": fill.id,
                    "filled_token_id": entry.token_id,
                    "filled_outcome": entry.outcome,
                }),
            )],
        ));
    };

    let mergeable_size = Decimal::min(yes_position.size, no_position.size)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if mergeable_size <= Decimal::ZERO {
        return Ok((Vec::new(), Vec::new()));
    }
    let already_planned_size = state
        .reward_bot_service
        .active_reward_merge_intent_size(&entry.account_id, &entry.condition_id)
        .await?
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    let merge_size = (mergeable_size - already_planned_size)
        .max(Decimal::ZERO)
        .round_dp_with_strategy(2, RoundingStrategy::ToZero);
    if merge_size <= Decimal::ZERO {
        return Ok((Vec::new(), Vec::new()));
    }

    let now = OffsetDateTime::now_utc();
    let (status, reason) = new_balanced_merge_intent_status_and_reason(config);
    let intent = RewardMergeIntent {
        id: format!("rewmerge_{}", sanitize_reward_id_fragment(&fill.id)),
        account_id: entry.account_id.clone(),
        condition_id: entry.condition_id.clone(),
        yes_token_id: yes_position.token_id.clone(),
        no_token_id: no_position.token_id.clone(),
        merge_size,
        yes_position_size: yes_position.size,
        no_position_size: no_position.size,
        yes_avg_price: yes_position.avg_price,
        no_avg_price: no_position.avg_price,
        status,
        reason,
        source_fill_id: fill.id.clone(),
        tx_hash: None,
        submitted_at: None,
        confirmed_at: None,
        failed_reason: None,
        retry_count: 0,
        trace_id: trace_id.to_string(),
        created_at: now,
        updated_at: now,
    };
    let event = reward_live_event(
        entry,
        "reward_live_balanced_merge_intent_created",
        RewardRiskSeverity::Warning,
        "created a balanced merge intent for paired YES/NO inventory",
        json!({
            "merge_intent_id": intent.id,
            "source_fill_id": fill.id,
            "yes_token_id": intent.yes_token_id,
            "no_token_id": intent.no_token_id,
            "merge_size": intent.merge_size,
            "yes_position_size": intent.yes_position_size,
            "no_position_size": intent.no_position_size,
            "already_planned_size": already_planned_size,
            "status": intent.status.as_str(),
        }),
    );

    Ok((vec![intent], vec![event]))
}

async fn plan_live_balanced_merge_intents_for_positions(
    state: &AppState,
    config: &RewardBotConfig,
    positions: &[RewardPosition],
    trace_id: &str,
) -> Result<(Vec<RewardMergeIntent>, Vec<RewardRiskEvent>)> {
    if !config.balanced_merge_enabled {
        return Ok((Vec::new(), Vec::new()));
    }

    let mut pairs: HashMap<(&str, &str), (Option<&RewardPosition>, Option<&RewardPosition>)> =
        HashMap::new();
    for position in positions
        .iter()
        .filter(|position| position.size > Decimal::ZERO)
    {
        let entry = pairs
            .entry((position.account_id.as_str(), position.condition_id.as_str()))
            .or_default();
        if position.outcome.trim().eq_ignore_ascii_case("yes") {
            entry.0 = Some(position);
        } else if position.outcome.trim().eq_ignore_ascii_case("no") {
            entry.1 = Some(position);
        }
    }

    let mut intents = Vec::new();
    let mut events = Vec::new();
    let mut sequence = 0usize;
    for ((account_id, condition_id), (yes_position, no_position)) in pairs {
        let (Some(yes_position), Some(no_position)) = (yes_position, no_position) else {
            continue;
        };
        let mergeable_size = Decimal::min(yes_position.size, no_position.size)
            .round_dp_with_strategy(2, RoundingStrategy::ToZero);
        if mergeable_size <= Decimal::ZERO {
            continue;
        }
        let already_planned_size = state
            .reward_bot_service
            .active_reward_merge_intent_size(account_id, condition_id)
            .await?
            .round_dp_with_strategy(2, RoundingStrategy::ToZero);
        let merge_size = (mergeable_size - already_planned_size)
            .max(Decimal::ZERO)
            .round_dp_with_strategy(2, RoundingStrategy::ToZero);
        if merge_size <= Decimal::ZERO {
            continue;
        }

        sequence += 1;
        let now = OffsetDateTime::now_utc();
        let (status, reason) = new_balanced_merge_intent_status_and_reason(config);
        let id = format!(
            "rewmerge_auto_{}_{}_{}",
            now.unix_timestamp_nanos(),
            sequence,
            sanitize_reward_id_fragment(trace_id)
        );
        let source_fill_id = format!("auto_{id}");
        let intent = RewardMergeIntent {
            id,
            account_id: account_id.to_string(),
            condition_id: condition_id.to_string(),
            yes_token_id: yes_position.token_id.clone(),
            no_token_id: no_position.token_id.clone(),
            merge_size,
            yes_position_size: yes_position.size,
            no_position_size: no_position.size,
            yes_avg_price: yes_position.avg_price,
            no_avg_price: no_position.avg_price,
            status,
            reason,
            source_fill_id,
            tx_hash: None,
            submitted_at: None,
            confirmed_at: None,
            failed_reason: None,
            retry_count: 0,
            trace_id: trace_id.to_string(),
            created_at: now,
            updated_at: now,
        };
        events.push(new_risk_event(
            Some(intent.account_id.clone()),
            Some(intent.condition_id.clone()),
            None,
            "reward_live_balanced_merge_intent_created",
            RewardRiskSeverity::Warning,
            "auto-created a balanced merge intent for existing paired YES/NO inventory",
            json!({
                "merge_intent_id": intent.id,
                "source_fill_id": intent.source_fill_id,
                "yes_token_id": intent.yes_token_id,
                "no_token_id": intent.no_token_id,
                "merge_size": intent.merge_size,
                "yes_position_size": intent.yes_position_size,
                "no_position_size": intent.no_position_size,
                "already_planned_size": already_planned_size,
                "status": intent.status.as_str(),
                "auto_discovered": true,
            }),
        ));
        intents.push(intent);
    }

    Ok((intents, events))
}

fn new_balanced_merge_intent_status_and_reason(
    config: &RewardBotConfig,
) -> (RewardMergeIntentStatus, String) {
    if config.balanced_merge_auto_execute_enabled {
        (
            RewardMergeIntentStatus::Pending,
            "balanced merge pair is ready for on-chain execution".to_string(),
        )
    } else {
        (
            RewardMergeIntentStatus::Unsupported,
            "balanced merge pair is ready, but automatic on-chain merge execution is disabled"
                .to_string(),
        )
    }
}

#[allow(clippy::too_many_arguments)]
fn reward_post_fill_strategy(
    config: &RewardBotConfig,
    plans: &[RewardQuotePlan],
    entry: &ManagedRewardOrder,
    fill_size: Decimal,
    positions: &HashMap<String, RewardPosition>,
    books: &HashMap<String, RewardOrderBook>,
    ai_min_confidence: Decimal,
) -> RewardPostFillStrategyDecision {
    let floor_price = reward_post_fill_exit_floor(entry, positions);
    if config.post_fill_strategy != PostFillStrategy::Adaptive {
        return RewardPostFillStrategyDecision {
            strategy: config.post_fill_strategy,
            source: RewardExitStrategySource::Configured,
            floor_price,
            adaptive_event: None,
        };
    }

    let decision = reward_adaptive_exit_decision(
        config,
        plans,
        entry,
        fill_size,
        floor_price,
        books,
        ai_min_confidence,
    );

    RewardPostFillStrategyDecision {
        strategy: decision.selected_strategy,
        source: RewardExitStrategySource::Adaptive,
        floor_price: decision.floor_price,
        adaptive_event: Some(reward_live_event(
            entry,
            "reward_live_adaptive_exit_selected",
            RewardRiskSeverity::Info,
            decision.reason.clone(),
            reward_adaptive_exit_decision_metadata(&decision),
        )),
    }
}

fn reward_adaptive_exit_decision(
    config: &RewardBotConfig,
    plans: &[RewardQuotePlan],
    order: &ManagedRewardOrder,
    exit_size: Decimal,
    floor_price: Decimal,
    books: &HashMap<String, RewardOrderBook>,
    ai_min_confidence: Decimal,
) -> AdaptiveExitDecision {
    let fallback_strategy = reward_adaptive_fallback_strategy(config);
    let plan = reward_exit_plan_for_order(plans, order);
    let exit_notional_usd = (floor_price * exit_size.max(Decimal::ZERO)).round_dp(4);
    let book = books.get(&order.token_id);
    let best_bid = reward_best_bid_tick(book);
    let best_ask = reward_best_ask_tick(book);
    let bid_depth_at_floor_usd = reward_bid_depth_at_or_above_usd(book, floor_price);
    let required_depth_usd = Decimal::max(
        config.adaptive_flatten_min_bid_depth_usd,
        (exit_notional_usd * config.adaptive_flatten_min_depth_multiple).round_dp(4),
    );
    let min_flatten_bid =
        floor_price + config.adaptive_flatten_min_surplus_cents / Decimal::from(100_u64);
    let can_flatten_non_loss = best_bid.is_some_and(|bid| bid >= min_flatten_bid)
        && bid_depth_at_floor_usd >= required_depth_usd;
    let hard_risk_reasons = reward_adaptive_hard_risk_reasons(config, plan, ai_min_confidence);
    let plan_ineligible = plan.is_some_and(|plan| !plan.eligible);
    let plan_healthy = plan.is_some_and(|plan| {
        plan.eligible
            && plan.quote_readiness == RewardQuoteReadiness::ReadyToQuote
            && plan.live_skip_reason.is_none()
            && hard_risk_reasons.is_empty()
    });

    let (selected_strategy, reason) = if can_flatten_non_loss
        && config.adaptive_flatten_when_event_risk
        && !hard_risk_reasons.is_empty()
    {
        (
            PostFillStrategy::FlattenImmediately,
            "non-loss bid depth covers exit and hard risk is elevated".to_string(),
        )
    } else if can_flatten_non_loss
        && config.adaptive_flatten_when_plan_ineligible
        && plan_ineligible
    {
        (
            PostFillStrategy::FlattenImmediately,
            "non-loss bid depth covers exit and quote plan is no longer eligible".to_string(),
        )
    } else if config.adaptive_hold_when_plan_eligible && plan_healthy {
        (
            PostFillStrategy::HoldAndRequote,
            "quote plan is still eligible; keeping a maker exit and normal quoting".to_string(),
        )
    } else if can_flatten_non_loss {
        (
            PostFillStrategy::FlattenImmediately,
            "non-loss bid depth covers exit and maker hold is not preferred".to_string(),
        )
    } else {
        (
            fallback_strategy,
            "adaptive flatten requirements are not met; using configured fallback".to_string(),
        )
    };

    AdaptiveExitDecision {
        selected_strategy,
        fallback_strategy,
        floor_price,
        best_bid,
        best_ask,
        exit_notional_usd,
        bid_depth_at_floor_usd,
        required_depth_usd,
        min_flatten_bid,
        can_flatten_non_loss,
        plan_eligible: plan.map(|plan| plan.eligible),
        quote_readiness: plan.map(|plan| plan.quote_readiness.as_str()),
        plan_ineligible,
        plan_healthy,
        hard_risk_reasons,
        reason,
    }
}

fn reward_adaptive_exit_decision_metadata(decision: &AdaptiveExitDecision) -> Value {
    json!({
        "selected_strategy": decision.selected_strategy.as_str(),
        "fallback_strategy": decision.fallback_strategy.as_str(),
        "floor_price": decision.floor_price,
        "best_bid": decision.best_bid,
        "best_ask": decision.best_ask,
        "exit_notional_usd": decision.exit_notional_usd,
        "bid_depth_at_floor_usd": decision.bid_depth_at_floor_usd,
        "required_depth_usd": decision.required_depth_usd,
        "min_flatten_bid": decision.min_flatten_bid,
        "can_flatten_non_loss": decision.can_flatten_non_loss,
        "plan_eligible": decision.plan_eligible,
        "quote_readiness": decision.quote_readiness,
        "plan_ineligible": decision.plan_ineligible,
        "plan_healthy": decision.plan_healthy,
        "risk_reasons": &decision.hard_risk_reasons,
        "reason": &decision.reason,
    })
}

#[allow(clippy::too_many_arguments)]
fn reselect_adaptive_exit_orders(
    config: &RewardBotConfig,
    plans: &[RewardQuotePlan],
    books: &HashMap<String, RewardOrderBook>,
    positions: &[RewardPosition],
    open_orders: &mut [ManagedRewardOrder],
    ai_min_confidence: Decimal,
    trace_id: &str,
    now: OffsetDateTime,
) -> Vec<LiveRewardOrderUpdate> {
    let mut updates = Vec::new();
    for order in open_orders.iter_mut() {
        if !adaptive_exit_reselection_candidate(order) {
            continue;
        }
        if !adaptive_exit_recheck_due(order, config, now) {
            continue;
        }

        let floor_price = reward_adaptive_exit_floor_for_order(order, positions);
        let exit_size = (order.size - order.filled_size)
            .max(Decimal::ZERO)
            .min(reward_sell_position_size(order, positions))
            .round_dp_with_strategy(2, RoundingStrategy::ToZero);
        if exit_size <= Decimal::ZERO {
            continue;
        }
        let decision = reward_adaptive_exit_decision(
            config,
            plans,
            order,
            exit_size,
            floor_price,
            books,
            ai_min_confidence,
        );
        let previous_strategy = order.exit_strategy_selected;
        if previous_strategy == Some(decision.selected_strategy) {
            continue;
        }

        if order.external_order_id.is_some() {
            updates.push(LiveRewardOrderUpdate::Unchanged(reward_live_event(
                order,
                "reward_live_adaptive_exit_reselect_deferred",
                RewardRiskSeverity::Info,
                "adaptive exit reselect deferred because the sell order has already been submitted",
                json!({
                    "previous_strategy": previous_strategy.map(PostFillStrategy::as_str),
                    "proposed_strategy": decision.selected_strategy.as_str(),
                    "cancel_replace_enabled": config.adaptive_exit_cancel_replace_enabled,
                    "trace_id": trace_id,
                    "decision": reward_adaptive_exit_decision_metadata(&decision),
                }),
            )));
            continue;
        }

        if adaptive_exit_reselect_cooldown_active(order, config, now) {
            let previous_updated_at = order.updated_at;
            order.reason = format!(
                "adaptive exit reselect deferred by cooldown; proposed {}",
                decision.selected_strategy.as_str()
            );
            order.updated_at = now;
            updates.push(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    order,
                    "reward_live_adaptive_exit_reselect_deferred",
                    RewardRiskSeverity::Info,
                    order.reason.clone(),
                    json!({
                        "previous_strategy": previous_strategy.map(PostFillStrategy::as_str),
                        "proposed_strategy": decision.selected_strategy.as_str(),
                        "previous_updated_at": previous_updated_at,
                        "last_reselected_at": order.exit_last_reselected_at,
                        "cooldown_sec": config.adaptive_exit_reselect_cooldown_sec,
                        "trace_id": trace_id,
                        "decision": reward_adaptive_exit_decision_metadata(&decision),
                    }),
                ),
            ));
            continue;
        }

        if order.exit_reselect_count
            >= i32::from(config.adaptive_exit_max_reselects_per_order)
        {
            order.reason = format!(
                "adaptive exit reselect limit reached; proposed {}",
                decision.selected_strategy.as_str()
            );
            order.updated_at = now;
            updates.push(LiveRewardOrderUpdate::Changed(
                order.clone(),
                reward_live_event(
                    order,
                    "reward_live_adaptive_exit_reselect_limit_reached",
                    RewardRiskSeverity::Warning,
                    order.reason.clone(),
                    json!({
                        "previous_strategy": previous_strategy.map(PostFillStrategy::as_str),
                        "proposed_strategy": decision.selected_strategy.as_str(),
                        "reselect_count": order.exit_reselect_count,
                        "max_reselects": config.adaptive_exit_max_reselects_per_order,
                        "trace_id": trace_id,
                        "decision": reward_adaptive_exit_decision_metadata(&decision),
                    }),
                ),
            ));
            continue;
        }

        if let Some(current_strategy) = previous_strategy
            && !adaptive_exit_reselection_is_material(config, current_strategy, &decision)
        {
            continue;
        }

        let previous_price = order.price;
        let previous_reselect_count = order.exit_reselect_count;
        order.price = reward_adaptive_exit_order_price(config, &decision);
        order.exit_strategy_selected = Some(decision.selected_strategy);
        order.exit_floor_price = Some(decision.floor_price);
        order.exit_reselect_count = order.exit_reselect_count.saturating_add(1);
        order.exit_last_reselected_at = Some(now);
        order.reason = reward_adaptive_exit_order_reason(&decision);
        order.updated_at = now;

        updates.push(LiveRewardOrderUpdate::Changed(
            order.clone(),
            reward_live_event(
                order,
                "reward_live_adaptive_exit_reselected",
                RewardRiskSeverity::Info,
                order.reason.clone(),
                json!({
                    "previous_strategy": previous_strategy.map(PostFillStrategy::as_str),
                    "selected_strategy": decision.selected_strategy.as_str(),
                    "previous_price": previous_price,
                    "price": order.price,
                    "previous_reselect_count": previous_reselect_count,
                    "reselect_count": order.exit_reselect_count,
                    "trace_id": trace_id,
                    "decision": reward_adaptive_exit_decision_metadata(&decision),
                }),
            ),
        ));
    }
    updates
}

fn adaptive_exit_reselection_candidate(order: &ManagedRewardOrder) -> bool {
    order.side == RewardOrderSide::Sell
        && order.status == ManagedRewardOrderStatus::ExitPending
        && order.exit_strategy_source == RewardExitStrategySource::Adaptive
}

fn adaptive_exit_recheck_due(
    order: &ManagedRewardOrder,
    config: &RewardBotConfig,
    now: OffsetDateTime,
) -> bool {
    let anchor = order
        .exit_last_reselected_at
        .filter(|last| *last > order.updated_at)
        .unwrap_or(order.updated_at);
    now >= anchor + reward_seconds_duration(config.adaptive_exit_recheck_sec)
}

fn adaptive_exit_reselect_cooldown_active(
    order: &ManagedRewardOrder,
    config: &RewardBotConfig,
    now: OffsetDateTime,
) -> bool {
    let Some(last_reselected_at) = order.exit_last_reselected_at else {
        return false;
    };
    now < last_reselected_at + reward_seconds_duration(config.adaptive_exit_reselect_cooldown_sec)
}

fn reward_seconds_duration(seconds: u64) -> TimeDuration {
    TimeDuration::seconds(i64::try_from(seconds).unwrap_or(i64::MAX))
}

fn reward_adaptive_exit_floor_for_order(
    order: &ManagedRewardOrder,
    positions: &[RewardPosition],
) -> Decimal {
    let position_floor = positions
        .iter()
        .find(|position| position.token_id == order.token_id)
        .map(|position| position.avg_price)
        .filter(|price| *price > Decimal::ZERO)
        .unwrap_or(Decimal::ZERO);
    if let Some(stored_floor) = order.exit_floor_price {
        return ceil_reward_price_to_tick(Decimal::max(stored_floor, position_floor));
    }
    reward_sell_exit_floor(order, positions)
}

fn adaptive_exit_reselection_is_material(
    config: &RewardBotConfig,
    current_strategy: PostFillStrategy,
    decision: &AdaptiveExitDecision,
) -> bool {
    if adaptive_exit_reselection_safety_override(current_strategy, decision) {
        return true;
    }
    let current_score = adaptive_exit_strategy_score_cents(config, current_strategy, decision);
    let next_score =
        adaptive_exit_strategy_score_cents(config, decision.selected_strategy, decision);
    next_score - current_score >= config.adaptive_exit_min_strategy_improvement_cents
}

fn adaptive_exit_reselection_safety_override(
    current_strategy: PostFillStrategy,
    decision: &AdaptiveExitDecision,
) -> bool {
    if decision.selected_strategy == PostFillStrategy::FlattenImmediately
        && decision.can_flatten_non_loss
        && (decision.plan_ineligible || !decision.hard_risk_reasons.is_empty())
    {
        return true;
    }
    if current_strategy == PostFillStrategy::FlattenImmediately
        && decision.selected_strategy != PostFillStrategy::FlattenImmediately
        && !decision.can_flatten_non_loss
    {
        return true;
    }
    decision.selected_strategy == PostFillStrategy::HoldAndRequote && decision.plan_healthy
}

fn adaptive_exit_strategy_score_cents(
    config: &RewardBotConfig,
    strategy: PostFillStrategy,
    decision: &AdaptiveExitDecision,
) -> Decimal {
    match strategy {
        PostFillStrategy::FlattenImmediately => {
            if !decision.can_flatten_non_loss {
                return Decimal::ZERO;
            }
            let surplus = decision
                .best_bid
                .map(|bid| ((bid - decision.floor_price) * Decimal::from(100_u64)).max(Decimal::ZERO))
                .unwrap_or_default();
            if decision.plan_ineligible || !decision.hard_risk_reasons.is_empty() {
                surplus + config.adaptive_exit_min_strategy_improvement_cents
            } else {
                surplus
            }
        }
        PostFillStrategy::HoldAndRequote => {
            if decision.plan_healthy {
                config.adaptive_exit_min_strategy_improvement_cents + Decimal::ONE
            } else {
                Decimal::ZERO
            }
        }
        PostFillStrategy::ExitAtMarkup => config.exit_markup_cents.max(Decimal::ZERO),
        PostFillStrategy::Adaptive => Decimal::ZERO,
    }
}

fn reward_adaptive_exit_order_price(
    config: &RewardBotConfig,
    decision: &AdaptiveExitDecision,
) -> Decimal {
    match decision.selected_strategy {
        PostFillStrategy::HoldAndRequote | PostFillStrategy::FlattenImmediately => {
            decision.floor_price
        }
        PostFillStrategy::ExitAtMarkup => ceil_reward_price_to_tick(Decimal::min(
            Decimal::from_parts(99, 0, 0, false, 2),
            decision.floor_price + config.exit_markup_cents / Decimal::from(100_u64),
        )),
        PostFillStrategy::Adaptive => decision.floor_price,
    }
}

fn reward_adaptive_exit_order_reason(decision: &AdaptiveExitDecision) -> String {
    match decision.selected_strategy {
        PostFillStrategy::HoldAndRequote => {
            "adaptive reselected hold-and-requote maker exit; post_only=true".to_string()
        }
        PostFillStrategy::ExitAtMarkup => {
            "adaptive reselected exit-at-markup maker exit; post_only=true".to_string()
        }
        PostFillStrategy::FlattenImmediately => {
            "adaptive reselected non-post-only flatten exit; post_only=false".to_string()
        }
        PostFillStrategy::Adaptive => {
            "adaptive exit reselect produced no concrete strategy".to_string()
        }
    }
}

fn reward_adaptive_fallback_strategy(config: &RewardBotConfig) -> PostFillStrategy {
    match config.adaptive_fallback_strategy {
        PostFillStrategy::Adaptive => PostFillStrategy::ExitAtMarkup,
        strategy => strategy,
    }
}

fn reward_exit_plan_for_order<'a>(
    plans: &'a [RewardQuotePlan],
    order: &ManagedRewardOrder,
) -> Option<&'a RewardQuotePlan> {
    plans.iter().find(|plan| {
        plan.condition_id == order.condition_id
            && plan.strategy_profile == order.strategy_profile
            && (plan.legs.is_empty() || plan.legs.iter().any(|leg| leg.token_id == order.token_id))
    })
}

fn reward_post_fill_exit_floor(
    entry: &ManagedRewardOrder,
    positions: &HashMap<String, RewardPosition>,
) -> Decimal {
    let position_floor = positions
        .get(&entry.token_id)
        .map(|position| position.avg_price)
        .filter(|price| *price > Decimal::ZERO)
        .unwrap_or(Decimal::ZERO);
    ceil_reward_price_to_tick(Decimal::max(entry.price, position_floor))
}

fn reward_bid_depth_at_or_above_usd(
    book: Option<&RewardOrderBook>,
    floor_price: Decimal,
) -> Decimal {
    book.map(|book| {
        book.bids
            .iter()
            .filter(|level| floor_reward_price_to_tick(level.price) >= floor_price)
            .map(|level| (level.price * level.size).round_dp(4))
            .sum()
    })
    .unwrap_or_default()
}

fn reward_adaptive_hard_risk_reasons(
    config: &RewardBotConfig,
    plan: Option<&RewardQuotePlan>,
    ai_min_confidence: Decimal,
) -> Vec<String> {
    let Some(plan) = plan else {
        return Vec::new();
    };

    let mut reasons = Vec::new();
    if let Some(live_skip_reason) = &plan.live_skip_reason {
        reasons.push(format!("live_orderbook: {live_skip_reason}"));
    }
    if let Some(fair_value) = &plan.fair_value
        && !fair_value.passed
    {
        reasons.push(format!("fair_value: {}", fair_value.reason));
    }
    if let Some(event_window) = &plan.event_window
        && matches!(
            event_window.status,
            RewardEventWindowStatus::StopNewQuotes
                | RewardEventWindowStatus::CancelOpenBuys
                | RewardEventWindowStatus::InEventWindow
                | RewardEventWindowStatus::PostEventCooldown
        )
    {
        reasons.push(format!("event_window: {}", event_window.status.as_str()));
    }
    if config.ai_advisory_enabled
        && let Some(advisory) = &plan.ai_advisory
        && advisory.suitability == RewardAiSuitability::Avoid
        && advisory.confidence >= ai_min_confidence
    {
        reasons.push("ai_advisory: avoid".to_string());
    }
    if config.info_risk_enabled
        && config.info_risk_mode == polyedge_application::RewardSelectionMode::Enforce
        && plan.reason.starts_with("info risk ")
    {
        reasons.push(format!("info_risk: {}", plan.reason));
    }
    reasons
}

fn live_exit_order(
    entry: &ManagedRewardOrder,
    size: Decimal,
    price: Decimal,
    reason: &str,
    trace_id: &str,
) -> ManagedRewardOrder {
    let now = OffsetDateTime::now_utc();
    ManagedRewardOrder {
        id: format!(
            "rewexit_{}_{}",
            now.unix_timestamp_nanos(),
            trace_id.trim_start_matches("trc_")
        ),
        account_id: entry.account_id.clone(),
        condition_id: entry.condition_id.clone(),
        token_id: entry.token_id.clone(),
        outcome: entry.outcome.clone(),
        side: RewardOrderSide::Sell,
        price,
        size,
        strategy_bucket: entry.strategy_bucket,
        strategy_profile: entry.strategy_profile,
        exit_strategy_source: RewardExitStrategySource::Configured,
        exit_strategy_selected: None,
        exit_floor_price: None,
        exit_reselect_count: 0,
        exit_last_reselected_at: None,
        external_order_id: None,
        status: ManagedRewardOrderStatus::Planned,
        scoring: false,
        reason: reason.to_string(),
        filled_size: Decimal::ZERO,
        reward_earned: Decimal::ZERO,
        last_scored_at: None,
        created_at: now,
        updated_at: now,
    }
}

#[allow(clippy::too_many_arguments)]
async fn cancel_sibling_live_reward_orders(
    connector: &LivePolymarketConnector,
    working_orders: &mut HashMap<String, ManagedRewardOrder>,
    filled_order: &ManagedRewardOrder,
    sibling_cancelled: &mut HashSet<String>,
    state: &AppState,
    account: &mut RewardAccountState,
    _positions: &HashMap<String, RewardPosition>,
    report: &mut RewardBotRunReport,
    trace_id: &str,
) -> Result<()> {
    let sibling_ids = working_orders
        .values()
        .filter(|order| {
            is_sibling_live_buy_order(order, filled_order)
                && sibling_cancelled.insert(order.id.clone())
        })
        .map(|order| order.id.clone())
        .collect::<Vec<_>>();

    for sibling_id in sibling_ids {
        let Some(sibling) = working_orders.get(&sibling_id).cloned() else {
            continue;
        };
        match cancel_one_live_reward_order(
            connector,
            sibling.clone(),
            "sibling rewards quote cancelled after live fill",
            trace_id,
        )
        .await?
        {
            LiveRewardOrderUpdate::Changed(order, event) => {
                working_orders.insert(order.id.clone(), order.clone());
                if !live_cancel_result_is_unknown(&order) {
                    report.cancelled_orders += 1;
                    report.risk_cancelled_orders += 1;
                }
                persist_live_reward_updates(
                    state,
                    account,
                    Vec::new(), // positions unchanged during sibling cancel
                    vec![order],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
            LiveRewardOrderUpdate::Unchanged(event)
            | LiveRewardOrderUpdate::Retryable(event) => {
                let sibling = mark_sibling_cancel_for_retry(sibling);
                working_orders.insert(sibling.id.clone(), sibling.clone());
                persist_live_reward_updates(
                    state,
                    account,
                    Vec::new(), // positions unchanged during sibling cancel
                    vec![sibling],
                    Vec::new(),
                    vec![event],
                    report,
                    trace_id,
                )
                .await?;
            }
        }
    }
    Ok(())
}

fn is_sibling_live_buy_order(
    candidate: &ManagedRewardOrder,
    filled_order: &ManagedRewardOrder,
) -> bool {
    candidate.id != filled_order.id
        && candidate.condition_id == filled_order.condition_id
        && candidate.token_id != filled_order.token_id
        && candidate.side == RewardOrderSide::Buy
        && candidate.status.is_open_like()
}

fn mark_sibling_cancel_for_retry(mut sibling: ManagedRewardOrder) -> ManagedRewardOrder {
    sibling.scoring = false;
    sibling.reason = format!(
        "{}; sibling cancellation must be retried after live fill",
        sibling.reason
    );
    sibling.updated_at = OffsetDateTime::now_utc();
    sibling
}

fn deferred_live_exit_is_post_only(order: &ManagedRewardOrder) -> bool {
    if let Some(strategy) = order.exit_strategy_selected {
        return strategy != PostFillStrategy::FlattenImmediately;
    }
    if order.reason.contains("post_only=false") || order.reason.contains("flatten") {
        return false;
    }
    order.reason.contains("post_only=true")
        || order.reason.contains("post-only")
        || order.reason.contains("original-price exit")
        || order.reason.contains("exit at markup")
}
