"use client";
import { useEffect, useState, useTransition } from "react";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createSubscription, listSubscriptions } from "@/lib/api/subscriptions";
import type { StrategySubscriptionData } from "@/lib/contracts/dto";

const ids = (value:string) => [...new Set(value.split(",").map(v=>Number(v.trim())).filter(Number.isSafeInteger))];
export function FollowingWorkbench(){const [items,setItems]=useState<StrategySubscriptionData[]>([]);const [strategyId,setStrategyId]=useState("");const [walletIds,setWalletIds]=useState("");const [until,setUntil]=useState("");const [error,setError]=useState("");const [pending,startTransition]=useTransition();const reload=()=>void listSubscriptions().then(r=>setItems(r.data)).catch(e=>setError(e instanceof Error?e.message:"跟随列表加载失败"));useEffect(reload,[]);const submit=()=>startTransition(async()=>{try{await createSubscription({source_strategy_id:Number(strategyId),wallet_ids:ids(walletIds),active_until:until?new Date(until).toISOString():undefined});setStrategyId("");setWalletIds("");reload()}catch(e){setError(e instanceof Error?e.message:"创建跟随失败")}});return <div className="space-y-8"><PageHeader eyebrow="策略同步" title="跟随策略" description="使用自己的钱包实时跟随源用户发布的策略版本和策略级操作；钱包风险与执行结果彼此隔离。"/><Card><CardHeader><CardTitle>开始跟随</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-4"><Input type="number" placeholder="源策略 ID" value={strategyId} onChange={e=>setStrategyId(e.target.value)}/><Input placeholder="钱包 ID，例如 1,2" value={walletIds} onChange={e=>setWalletIds(e.target.value)}/><Input type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/><Button disabled={pending||!strategyId||ids(walletIds).length===0} onClick={submit}>开始跟随</Button>{error?<p className="md:col-span-4 text-sm text-destructive">{error}</p>:null}</CardContent></Card><Card><CardHeader><CardTitle>我的跟随</CardTitle></CardHeader><CardContent className="space-y-3">{items.map(item=>{const i=item.subscription;return <div key={i.id} className="grid gap-2 rounded-md border p-4 text-sm md:grid-cols-5"><div><p className="font-medium">{i.source_strategy_name}</p><p className="text-xs text-muted-foreground">{i.source_display_name}</p></div><span>{i.status}</span><span>{i.kind}</span><span>{item.wallets.length} 个钱包</span><span>{new Date(i.effective_active_until).toLocaleString()}</span></div>})}</CardContent></Card></div>}
