import "server-only";

import type {
  ApprovalDto,
  ArbitrageAnalysisRunDto,
  ArbitrageOpportunityDto,
  ArbitrageScanDto,
  EventDto,
  EvidenceDto,
  MarketDto,
  NewsRawEventDto,
  NewsSourceHealthDto,
  PositionDto,
  ReplayRunDto,
  RiskAlertDto,
  RiskBucketDto,
  RiskStateDto,
  SignalDto,
} from "@/lib/contracts/dto";

const NOW = "2026-04-16T14:30:00Z";

export const marketFixtures: MarketDto[] = [
  {
    id: "mkt_120",
    question: "Will BTC close above 95k on Apr 30?",
    category: "Crypto",
    status: "open",
    best_bid: "0.51",
    best_ask: "0.53",
    mid_price: "0.52",
    volume_24h: "125000.00",
    ambiguity_level: "low",
    tradability_status: "tradable",
    resolution_source: "Polymarket BTC settlement reference close.",
    edge_case_notes: ["Low ambiguity market.", "Resolution uses published close methodology."],
    updated_at: NOW,
    version: 12,
  },
  {
    id: "mkt_121",
    question: "Will SEC approve ETH staking ETF by Q2?",
    category: "Regulation",
    status: "open",
    best_bid: "0.40",
    best_ask: "0.42",
    mid_price: "0.41",
    volume_24h: "98400.00",
    ambiguity_level: "medium",
    tradability_status: "manual_review",
    resolution_source: "Official SEC filing or public approval announcement.",
    edge_case_notes: [
      "Delayed filing language may not equal approval.",
      "Conditional launch wording requires operator review.",
      "Partial scope approval should be escalated.",
    ],
    updated_at: NOW,
    version: 9,
  },
  {
    id: "mkt_122",
    question: "Will the Fed cut rates in June?",
    category: "Macro",
    status: "open",
    best_bid: "0.62",
    best_ask: "0.64",
    mid_price: "0.63",
    volume_24h: "141200.00",
    ambiguity_level: "high",
    tradability_status: "observe_only",
    resolution_source: "FOMC target rate decision.",
    edge_case_notes: [
      "Interpretation risk around corridor adjustments.",
      "Observe only until macro source stabilizes.",
    ],
    updated_at: NOW,
    version: 7,
  },
  {
    id: "mkt_123",
    question: "Will the White House publish a formal AI executive order by May 31?",
    category: "Policy",
    status: "open",
    best_bid: "0.36",
    best_ask: "0.39",
    mid_price: "0.38",
    volume_24h: "54200.00",
    ambiguity_level: "high",
    tradability_status: "blocked",
    resolution_source: "Official White House release log and executive order registry.",
    edge_case_notes: [
      "Draft memos do not satisfy settlement unless a formal executive order is published.",
      "Block automation until the official publication source is stable again.",
    ],
    updated_at: NOW,
    version: 5,
  },
];

export const arbitrageScanFixtures: ArbitrageScanDto[] = [
  {
    id: "scan_mock_20260416_1430",
    started_at: "2026-04-16T14:29:45Z",
    finished_at: "2026-04-16T14:29:58Z",
    market_count: 4,
    snapshot_count: 4,
    opportunity_count: 3,
    scanner_version: "arbitrage-radar-v0",
    metadata: {
      connector: "polymarket",
      mode: "opportunity_detection_only",
    },
    trace_id: "trc_mock_arb_scan_1430",
  },
  {
    id: "scan_mock_20260416_1425",
    started_at: "2026-04-16T14:24:45Z",
    finished_at: "2026-04-16T14:24:59Z",
    market_count: 4,
    snapshot_count: 4,
    opportunity_count: 1,
    scanner_version: "arbitrage-radar-v0",
    metadata: {
      connector: "polymarket",
      mode: "opportunity_detection_only",
    },
    trace_id: "trc_mock_arb_scan_1425",
  },
  {
    id: "scan_mock_20260416_1420",
    started_at: "2026-04-16T14:19:45Z",
    finished_at: "2026-04-16T14:19:57Z",
    market_count: 4,
    snapshot_count: 4,
    opportunity_count: 0,
    scanner_version: "arbitrage-radar-v0",
    metadata: {
      connector: "polymarket",
      mode: "opportunity_detection_only",
    },
    trace_id: "trc_mock_arb_scan_1420",
  },
];

export const arbitrageOpportunityFixtures: ArbitrageOpportunityDto[] = [
  {
    id: "arb_mock_mkt_120_buy_both",
    scan_id: "scan_mock_20260416_1430",
    market_id: "mkt_120",
    opportunity_type: "binary_buy_both",
    status: "observed",
    gross_edge: "0.0400",
    price_sum: "0.9600",
    capacity: "850.00",
    yes_price: "0.45",
    no_price: "0.51",
    yes_size: "900.00",
    no_size: "850.00",
    observed_at: "2026-04-16T14:29:55Z",
    reason_codes: ["yes_ask_plus_no_ask_below_one"],
    analysis_payload: {
      formula: "1 - yes_ask - no_ask",
      yes_ask: "0.45",
      no_ask: "0.51",
      price_sum: "0.9600",
      gross_edge: "0.0400",
    },
    trace_id: "trc_mock_arb_scan_1430",
    validation: {
      id: "arb_val_mock_mkt_120_buy_both",
      opportunity_id: "arb_mock_mkt_120_buy_both",
      status: "valid",
      gross_edge: "0.0400",
      net_edge: "0.0300",
      fee_estimate: "0.0050",
      slippage_buffer: "0.0050",
      validated_capacity: "850.00",
      book_age_ms: 320,
      reason_codes: ["net_edge_positive_after_buffers"],
      validation_payload: { source: "mock" },
      validated_at: "2026-04-16T14:29:55Z",
      trace_id: "trc_mock_arb_scan_1430",
    },
  },
  {
    id: "arb_mock_mkt_121_sell_both",
    scan_id: "scan_mock_20260416_1430",
    market_id: "mkt_121",
    opportunity_type: "binary_sell_both",
    status: "observed",
    gross_edge: "0.0250",
    price_sum: "1.0250",
    capacity: "520.00",
    yes_price: "0.44",
    no_price: "0.585",
    yes_size: "620.00",
    no_size: "520.00",
    observed_at: "2026-04-16T14:29:54Z",
    reason_codes: ["yes_bid_plus_no_bid_above_one"],
    analysis_payload: {
      formula: "yes_bid + no_bid - 1",
      yes_bid: "0.44",
      no_bid: "0.585",
      price_sum: "1.0250",
      gross_edge: "0.0250",
    },
    trace_id: "trc_mock_arb_scan_1430",
    validation: {
      id: "arb_val_mock_mkt_121_sell_both",
      opportunity_id: "arb_mock_mkt_121_sell_both",
      status: "valid",
      gross_edge: "0.0250",
      net_edge: "0.0150",
      fee_estimate: "0.0050",
      slippage_buffer: "0.0050",
      validated_capacity: "520.00",
      book_age_ms: 410,
      reason_codes: ["net_edge_positive_after_buffers"],
      validation_payload: { source: "mock" },
      validated_at: "2026-04-16T14:29:54Z",
      trace_id: "trc_mock_arb_scan_1430",
    },
  },
  {
    id: "arb_mock_mkt_122_buy_both",
    scan_id: "scan_mock_20260416_1430",
    market_id: "mkt_122",
    opportunity_type: "binary_buy_both",
    status: "observed",
    gross_edge: "0.0150",
    price_sum: "0.9850",
    capacity: "420.00",
    yes_price: "0.61",
    no_price: "0.375",
    yes_size: "480.00",
    no_size: "420.00",
    observed_at: "2026-04-16T14:29:52Z",
    reason_codes: ["yes_ask_plus_no_ask_below_one"],
    analysis_payload: {
      formula: "1 - yes_ask - no_ask",
      yes_ask: "0.61",
      no_ask: "0.375",
      price_sum: "0.9850",
      gross_edge: "0.0150",
    },
    trace_id: "trc_mock_arb_scan_1430",
    validation: {
      id: "arb_val_mock_mkt_122_buy_both",
      opportunity_id: "arb_mock_mkt_122_buy_both",
      status: "insufficient_depth",
      gross_edge: "0.0150",
      net_edge: "0.0050",
      fee_estimate: "0.0050",
      slippage_buffer: "0.0050",
      validated_capacity: "0.00",
      book_age_ms: 520,
      reason_codes: ["capacity_below_threshold"],
      validation_payload: { source: "mock" },
      validated_at: "2026-04-16T14:29:52Z",
      trace_id: "trc_mock_arb_scan_1430",
    },
  },
  {
    id: "arb_mock_mkt_120_buy_both_1425",
    scan_id: "scan_mock_20260416_1425",
    market_id: "mkt_120",
    opportunity_type: "binary_buy_both",
    status: "repeated",
    gross_edge: "0.0180",
    price_sum: "0.9820",
    capacity: "300.00",
    yes_price: "0.47",
    no_price: "0.512",
    yes_size: "360.00",
    no_size: "300.00",
    observed_at: "2026-04-16T14:24:55Z",
    reason_codes: ["yes_ask_plus_no_ask_below_one"],
    analysis_payload: {
      formula: "1 - yes_ask - no_ask",
      yes_ask: "0.47",
      no_ask: "0.512",
      price_sum: "0.9820",
      gross_edge: "0.0180",
    },
    trace_id: "trc_mock_arb_scan_1425",
    validation: {
      id: "arb_val_mock_mkt_120_buy_both_1425",
      opportunity_id: "arb_mock_mkt_120_buy_both_1425",
      status: "stale_book",
      gross_edge: "0.0180",
      net_edge: "0.0080",
      fee_estimate: "0.0050",
      slippage_buffer: "0.0050",
      validated_capacity: "0.00",
      book_age_ms: 14500,
      reason_codes: ["book_age_exceeds_threshold"],
      validation_payload: { source: "mock" },
      validated_at: "2026-04-16T14:25:09Z",
      trace_id: "trc_mock_arb_scan_1425",
    },
  },
];

export const arbitrageAnalysisRunFixtures: ArbitrageAnalysisRunDto[] = [
  {
    id: "arb_analysis_mock_20260416_1430",
    generated_at: NOW,
    lookback_hours: 24,
    opportunity_count: 4,
    market_count: 3,
    summary_payload: {
      generated_at: NOW,
      lookback_hours: 24,
      opportunity_count: 4,
      market_count: 3,
      type_counts: [
        { opportunity_type: "binary_buy_both", count: 3 },
        { opportunity_type: "binary_sell_both", count: 1 },
      ],
      top_markets: [
        {
          market_id: "mkt_120",
          opportunity_count: 2,
          first_observed_at: "2026-04-16T14:24:55Z",
          last_observed_at: "2026-04-16T14:29:55Z",
          duration_seconds: 300,
          max_gross_edge: "0.0400",
          avg_gross_edge: "0.0290",
          max_capacity: "850.00",
          avg_capacity: "575.00",
        },
        {
          market_id: "mkt_121",
          opportunity_count: 1,
          first_observed_at: "2026-04-16T14:29:54Z",
          last_observed_at: "2026-04-16T14:29:54Z",
          duration_seconds: 0,
          max_gross_edge: "0.0250",
          avg_gross_edge: "0.0250",
          max_capacity: "520.00",
          avg_capacity: "520.00",
        },
        {
          market_id: "mkt_122",
          opportunity_count: 1,
          first_observed_at: "2026-04-16T14:29:52Z",
          last_observed_at: "2026-04-16T14:29:52Z",
          duration_seconds: 0,
          max_gross_edge: "0.0150",
          avg_gross_edge: "0.0150",
          max_capacity: "420.00",
          avg_capacity: "420.00",
        },
      ],
    },
    trace_id: "trc_mock_arb_analysis_1430",
  },
];

export const eventFixtures: EventDto[] = [
  {
    id: "evt_9001",
    source: "reuters",
    summary: "Senior SEC staff signals concerns over ETH staking disclosures.",
    relevance_score: "0.81",
    confidence: "0.78",
    status: "active",
    related_market_ids: ["mkt_121"],
    reason_trace: "Official language changes settlement path relevance and supports a lower approval probability.",
    created_at: "2026-04-16T13:42:00Z",
    updated_at: NOW,
    version: 3,
  },
  {
    id: "evt_9002",
    source: "fomc_calendar",
    summary: "Fed speakers reinforce patience narrative ahead of June meeting.",
    relevance_score: "0.74",
    confidence: "0.69",
    status: "superseded",
    related_market_ids: ["mkt_122"],
    reason_trace: "Original macro take was superseded by newer desk notes after rate path wording changed.",
    created_at: "2026-04-16T13:27:00Z",
    updated_at: NOW,
    version: 4,
  },
  {
    id: "evt_9003",
    source: "x_whitelist",
    summary: "Market influencers push BTC breakout narrative after ETF inflows.",
    relevance_score: "0.46",
    confidence: "0.44",
    status: "expired",
    related_market_ids: ["mkt_120"],
    reason_trace: "Social chatter is directionally aligned, but evidence quality is too weak for autonomous weighting.",
    created_at: "2026-04-16T13:08:00Z",
    updated_at: NOW,
    version: 2,
  },
  {
    id: "evt_9004",
    source: "official_gov_feed",
    summary: "Draft policy memo was retracted after publication metadata proved incorrect.",
    relevance_score: "0.67",
    confidence: "0.72",
    status: "invalidated",
    related_market_ids: ["mkt_123"],
    reason_trace: "Upstream source inconsistency invalidates the settlement path assumption and blocks automation.",
    created_at: "2026-04-16T12:51:00Z",
    updated_at: NOW,
    version: 2,
  },
];

export const newsSourceHealthFixtures: NewsSourceHealthDto[] = [
  {
    source: "sec_feed",
    source_type: "official",
    enabled: true,
    reliability: "0.95",
    last_success_at: "2026-04-16T14:24:00Z",
    last_error_at: null,
    consecutive_failures: 0,
    items_fetched: 18,
    items_inserted: 12,
    items_deduped: 6,
    health_score: "0.95",
    last_error: null,
    updated_at: "2026-04-16T14:24:00Z",
  },
  {
    source: "wire_feed",
    source_type: "news",
    enabled: true,
    reliability: "0.88",
    last_success_at: "2026-04-16T14:12:00Z",
    last_error_at: "2026-04-16T14:27:00Z",
    consecutive_failures: 1,
    items_fetched: 42,
    items_inserted: 31,
    items_deduped: 11,
    health_score: "0.68",
    last_error: "upstream timeout",
    updated_at: "2026-04-16T14:27:00Z",
  },
  {
    source: "calendar_watch",
    source_type: "calendar",
    enabled: true,
    reliability: "0.82",
    last_success_at: "2026-04-16T13:50:00Z",
    last_error_at: null,
    consecutive_failures: 0,
    items_fetched: 9,
    items_inserted: 9,
    items_deduped: 0,
    health_score: "0.82",
    last_error: null,
    updated_at: "2026-04-16T13:50:00Z",
  },
];

export const newsRawEventFixtures: NewsRawEventDto[] = [
  {
    id: "raw_news_sec_feed_f83d2a4a10c44a21",
    source: "sec_feed",
    source_type: "official",
    external_id: "sec-2026-calendar-1",
    title: "SEC publishes ETF calendar update",
    url: "https://example.com/sec-calendar",
    author: null,
    published_at: "2026-04-16T14:18:00Z",
    event_time: "2026-04-16T14:18:00Z",
    hash: "f83d2a4a10c44a21a4732b74d9e10ecf",
    raw_payload: {
      entry_id: "sec-2026-calendar-1",
      summary: "Review window narrowed for two pending ETF decisions.",
      feed_url: "https://example.com/sec.rss",
    },
    ingested_at: "2026-04-16T14:24:00Z",
    trace_id: "trc_mock_news_sec",
  },
  {
    id: "raw_news_wire_feed_153fc3bd4900ac82",
    source: "wire_feed",
    source_type: "news",
    external_id: "wire-policy-1",
    title: "Wire reports crypto policy hearing",
    url: "https://example.com/wire-policy",
    author: "Market Desk",
    published_at: "2026-04-16T14:05:00Z",
    event_time: "2026-04-16T14:05:00Z",
    hash: "153fc3bd4900ac82cb7d7ff406e88140",
    raw_payload: {
      entry_id: "wire-policy-1",
      summary: "Committee hearing was added to next week's calendar.",
      feed_url: "https://example.com/wire.rss",
    },
    ingested_at: "2026-04-16T14:12:00Z",
    trace_id: "trc_mock_news_wire",
  },
  {
    id: "raw_news_calendar_watch_d0a4bf6a9f6ef41d",
    source: "calendar_watch",
    source_type: "calendar",
    external_id: "fomc-calendar-1",
    title: "FOMC calendar updated",
    url: "https://example.com/fomc-calendar",
    author: null,
    published_at: "2026-04-16T13:44:00Z",
    event_time: "2026-04-16T13:44:00Z",
    hash: "d0a4bf6a9f6ef41d00ed3a1016c9121f",
    raw_payload: {
      entry_id: "fomc-calendar-1",
      summary: "Settlement-relevant macro calendar changed.",
      feed_url: "https://example.com/calendar.atom",
    },
    ingested_at: "2026-04-16T13:50:00Z",
    trace_id: "trc_mock_news_calendar",
  },
];

export const evidenceFixtures: EvidenceDto[] = [
  {
    id: "evd_5001",
    market_id: "mkt_121",
    event_id: "evt_9001",
    direction: "supports_no",
    strength: "0.34",
    source_reliability: "0.90",
    novelty: "0.80",
    resolution_relevance: "0.91",
    status: "active",
    expires_at: "2026-04-16T18:30:00Z",
    created_at: "2026-04-16T13:43:00Z",
    updated_at: NOW,
    version: 2,
  },
  {
    id: "evd_5002",
    market_id: "mkt_121",
    event_id: "evt_9001",
    direction: "background",
    strength: "0.18",
    source_reliability: "0.42",
    novelty: "0.55",
    resolution_relevance: "0.30",
    status: "active",
    expires_at: "2026-04-16T16:00:00Z",
    created_at: "2026-04-16T13:44:00Z",
    updated_at: NOW,
    version: 1,
  },
  {
    id: "evd_5003",
    market_id: "mkt_122",
    event_id: "evt_9002",
    direction: "supports_no",
    strength: "0.27",
    source_reliability: "0.86",
    novelty: "0.52",
    resolution_relevance: "0.88",
    status: "active",
    expires_at: "2026-04-16T20:00:00Z",
    created_at: "2026-04-16T13:30:00Z",
    updated_at: NOW,
    version: 2,
  },
  {
    id: "evd_5004",
    market_id: "mkt_120",
    event_id: "evt_9003",
    direction: "supports_yes",
    strength: "0.12",
    source_reliability: "0.35",
    novelty: "0.41",
    resolution_relevance: "0.25",
    status: "active",
    expires_at: "2026-04-16T15:00:00Z",
    created_at: "2026-04-16T13:10:00Z",
    updated_at: NOW,
    version: 1,
  },
];

export const signalFixtures: SignalDto[] = [
  {
    id: "sig_2411",
    market_id: "mkt_120",
    event_id: "evt_9003",
    action: "buy",
    side: "yes",
    market_price: "0.52",
    fair_price: "0.58",
    edge: "0.06",
    confidence: "0.88",
    lifecycle_state: "active",
    reason: "ETF inflow narrative still supports underpriced upside participation.",
    risk_decision: "Eligible for automated execution under current bucket limits.",
    evidence_ids: ["evd_5004"],
    updated_at: NOW,
    version: 9,
  },
  {
    id: "sig_2412",
    market_id: "mkt_121",
    event_id: "evt_9001",
    action: "buy",
    side: "no",
    market_price: "0.41",
    fair_price: "0.35",
    edge: "-0.06",
    confidence: "0.62",
    lifecycle_state: "new",
    reason: "Official update increases review-delay odds more than current price reflects.",
    risk_decision: "Signal is queued for manual review because settlement ambiguity is medium and theme exposure is elevated.",
    evidence_ids: ["evd_5001", "evd_5002"],
    updated_at: NOW,
    version: 9,
  },
  {
    id: "sig_2413",
    market_id: "mkt_120",
    event_id: "evt_9003",
    action: "buy",
    side: "yes",
    market_price: "0.28",
    fair_price: "0.30",
    edge: "0.02",
    confidence: "0.44",
    lifecycle_state: "weakened",
    reason: "Momentum evidence remains directionally positive but confidence decayed after contradictory flow.",
    risk_decision: "Watch only until confidence recovers above activation threshold.",
    evidence_ids: ["evd_5004"],
    updated_at: NOW,
    version: 4,
  },
  {
    id: "sig_2414",
    market_id: "mkt_122",
    event_id: "evt_9002",
    action: "buy",
    side: "no",
    market_price: "0.63",
    fair_price: "0.57",
    edge: "-0.06",
    confidence: "0.53",
    lifecycle_state: "reversed",
    reason: "Macro drift remains negative for cuts, but live macro feed instability invalidates autonomous posture.",
    risk_decision: "Reversed to manual monitoring because upstream data quality is degraded.",
    evidence_ids: ["evd_5003"],
    updated_at: NOW,
    version: 6,
  },
];

export const riskStateFixture: RiskStateDto = {
  id: "risk_state_global",
  mode: "manual_confirm",
  environment: "production",
  kill_switch: false,
  daily_pnl: "14200.00",
  gross_exposure: "0.62",
  net_exposure: "0.11",
  open_alerts: 3,
  daily_loss_limit: "1500000.00",
  daily_loss_used: "1260000.00",
  updated_at: NOW,
  version: 15,
};

export const approvalFixtures: ApprovalDto[] = [
  {
    id: "apr_001",
    type: "signal",
    severity: "critical",
    owner: "Risk Engine",
    resource_id: "sig_2412",
    summary: "ETH staking ETF short requires manual confirmation due to ambiguity.",
    status: "pending",
    requires_step_up_auth: true,
    created_at: "2026-04-16T14:02:11Z",
    updated_at: NOW,
    version: 3,
  },
  {
    id: "apr_002",
    type: "mode_switch",
    severity: "warning",
    owner: "Ops Desk",
    resource_id: "runtime_mode",
    summary: "Request to switch runtime from paper_trade to manual_confirm.",
    status: "pending",
    requires_step_up_auth: true,
    created_at: "2026-04-16T13:56:02Z",
    updated_at: NOW,
    version: 2,
  },
  {
    id: "apr_003",
    type: "kill_switch",
    severity: "critical",
    owner: "Latency Watch",
    resource_id: "kill_switch_global",
    summary: "Potential market data stale condition across macro markets.",
    status: "pending",
    requires_step_up_auth: true,
    created_at: "2026-04-16T13:48:17Z",
    updated_at: NOW,
    version: 5,
  },
  {
    id: "apr_004",
    type: "signal",
    severity: "info",
    owner: "Operator Desk",
    resource_id: "sig_2411",
    summary: "BTC breakout long was approved for automatic release after operator review.",
    status: "approved",
    requires_step_up_auth: false,
    created_at: "2026-04-16T13:22:44Z",
    updated_at: NOW,
    version: 2,
  },
  {
    id: "apr_005",
    type: "mode_switch",
    severity: "warning",
    owner: "Risk Admin",
    resource_id: "runtime_mode",
    summary: "Request to switch into live auto was rejected because risk alerts were unresolved.",
    status: "rejected",
    requires_step_up_auth: true,
    created_at: "2026-04-16T12:58:10Z",
    updated_at: NOW,
    version: 4,
  },
];

export const riskAlertFixtures: RiskAlertDto[] = [
  {
    id: "alt_101",
    severity: "critical",
    reason: "Daily loss usage reached 84% of configured limit.",
    target: "Global Risk",
    status: "unresolved",
    created_at: "2026-04-16T14:22:01Z",
    updated_at: NOW,
    version: 11,
  },
  {
    id: "alt_102",
    severity: "warning",
    reason: "Stale market snapshots detected in one macro source.",
    target: "Data Layer",
    status: "watching",
    created_at: "2026-04-16T14:11:44Z",
    updated_at: NOW,
    version: 6,
  },
  {
    id: "alt_103",
    severity: "warning",
    reason: "Event cluster exposure above preferred threshold.",
    target: "ETH ETF Theme",
    status: "contained",
    created_at: "2026-04-16T13:58:09Z",
    updated_at: NOW,
    version: 8,
  },
];

export const positionFixtures: PositionDto[] = [
  {
    id: "pos_001",
    market_id: "mkt_120",
    market_question: "Will BTC close above 95k on Apr 30?",
    side: "yes",
    quantity: "12500",
    average_cost: "0.48",
    mark_price: "0.52",
    realized_pnl: "4110.00",
    unrealized_pnl: "3190.00",
    bucket_name: "Crypto Momentum",
    updated_at: NOW,
    version: 4,
  },
  {
    id: "pos_002",
    market_id: "mkt_121",
    market_question: "Will SEC approve ETH staking ETF by Q2?",
    side: "no",
    quantity: "8200",
    average_cost: "0.39",
    mark_price: "0.41",
    realized_pnl: "-420.00",
    unrealized_pnl: "-820.00",
    bucket_name: "Regulation",
    updated_at: NOW,
    version: 3,
  },
  {
    id: "pos_003",
    market_id: "mkt_122",
    market_question: "Will the Fed cut rates in June?",
    side: "no",
    quantity: "6000",
    average_cost: "0.59",
    mark_price: "0.63",
    realized_pnl: "420.00",
    unrealized_pnl: "500.00",
    bucket_name: "Macro",
    updated_at: NOW,
    version: 2,
  },
];

export const riskBucketFixtures: RiskBucketDto[] = [
  {
    id: "bucket_crypto_momentum",
    name: "Crypto Momentum",
    exposure: "0.31",
    limit: "0.35",
    utilization: "0.89",
    status: "healthy",
    updated_at: NOW,
    version: 1,
  },
  {
    id: "bucket_regulation",
    name: "Regulation",
    exposure: "0.24",
    limit: "0.25",
    utilization: "0.96",
    status: "watch",
    updated_at: NOW,
    version: 1,
  },
  {
    id: "bucket_macro",
    name: "Macro",
    exposure: "0.18",
    limit: "0.18",
    utilization: "1.00",
    status: "breach",
    updated_at: NOW,
    version: 1,
  },
  {
    id: "bucket_election",
    name: "Election",
    exposure: "0.09",
    limit: "0.20",
    utilization: "0.45",
    status: "healthy",
    updated_at: NOW,
    version: 1,
  },
];

export const replayRunFixture: ReplayRunDto = {
  id: "run_2026_04_16_alpha",
  label: "run_2026_04_16_alpha",
  market_id: "mkt_121",
  market_question: "Will SEC approve ETH staking ETF by Q2?",
  prior: "0.41",
  posterior: "0.35",
  signal_state_from: "active",
  signal_state_to: "new",
  signal_hit_rate: "0.63",
  brier_score: "0.18",
  net_alpha: "0.024",
  timeline: [
    {
      occurred_at: "2026-04-16T13:42:00Z",
      kind: "event_ingested",
      summary: "Event ingested from Reuters feed.",
    },
    {
      occurred_at: "2026-04-16T13:43:00Z",
      kind: "evidence_generated",
      summary: "Evidence generated with supports_no direction.",
    },
    {
      occurred_at: "2026-04-16T13:44:00Z",
      kind: "posterior_updated",
      summary: "Posterior moved from 0.41 to 0.35.",
    },
    {
      occurred_at: "2026-04-16T13:45:00Z",
      kind: "signal_transition",
      summary: "Signal was emitted and linked to the manual approval queue.",
    },
  ],
  created_at: "2026-04-16T13:42:00Z",
  updated_at: NOW,
  version: 2,
};
